const SUPABASE_URL='https://yifgptxujimzsjoeghte.supabase.co';
const SUPABASE_KEY='sb_publishable_TGA26mIiNQ686GJrvQI3aw_PmfP8V1-';
const ADMIN_EMAIL='juliosirlene43@gmail.com';
const ADMIN_USER='admin';
const SESSION_KEY='jstech_supabase_session';
let session=null,clients=[],renewals=[],resellers=[],activeFilter='todos',dashboardPeriod='30d',messageClientId=null,clientDataId=null,androidApps=[];
const DEVICE_MARKER='__JSTECH_DEVICES__',DIRECT_RESELLER='Cliente direto';let clientDataText='';
const NO_MAC_APPS=new Set(['jjplayer','duotv','multbox','sync21player','upplay','max21','xciptvplayer','dunaxpt','touroboxmod','touroboxt7v5','xplus70','youcinemod','touroboxv2','unirevenda','gpcpro']);
const $=id=>document.getElementById(id);
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
const dateBR=date=>date?new Intl.DateTimeFormat('pt-BR').format(parseDate(date)):'—';
const today=()=>{const d=new Date();d.setHours(0,0,0,0);return d};
const isoToday=()=>formatISO(today());
function parseDate(value){const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)}
function formatISO(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function shiftDays(date,days){const d=new Date(date);d.setDate(d.getDate()+days);return d}
function periodBounds(type=dashboardPeriod){const now=today();let start,end=new Date(now);if(type==='lastMonth'){start=new Date(now.getFullYear(),now.getMonth()-1,1);end=new Date(now.getFullYear(),now.getMonth(),0)}else if(type==='month'){start=new Date(now.getFullYear(),now.getMonth(),1)}else if(type==='all'){start=new Date(2000,0,1)}else if(type==='custom'){start=$('periodStart').value?parseDate($('periodStart').value):new Date(now.getFullYear(),now.getMonth(),1);end=$('periodEnd').value?parseDate($('periodEnd').value):now}else{start=shiftDays(now,-29)}return{start,end}}
function inRange(value,range){if(!value)return false;const d=parseDate(String(value).slice(0,10));return d>=range.start&&d<=range.end}
function previousBounds(range){const days=Math.round((range.end-range.start)/86400000)+1;return{start:shiftDays(range.start,-days),end:shiftDays(range.start,-1)}}
function planMonths(plan){return({'30d':1,'3m':3,'6m':6,'1y':12})[plan]||1}
function trendText(current,previous){if(!previous)return current?'Primeiro resultado neste comparativo':'Sem movimentação anterior';const pct=Math.round(((current-previous)/previous)*100);return `${pct>=0?'+':''}${pct}% vs. período anterior`}
function diffDays(date){return Math.round((parseDate(date)-today())/86400000)}
function planLabel(plan){return ({'30d':'30 dias','3m':'3 meses','6m':'6 meses','1y':'1 ano'})[plan]||plan}
function addMonths(date,months){const day=date.getDate();date.setDate(1);date.setMonth(date.getMonth()+months);const last=new Date(date.getFullYear(),date.getMonth()+1,0).getDate();date.setDate(Math.min(day,last))}
function calculateDue(start,plan){const d=parseDate(start);if(plan==='30d')d.setDate(d.getDate()+30);if(plan==='3m')addMonths(d,3);if(plan==='6m')addMonths(d,6);if(plan==='1y')addMonths(d,12);return formatISO(d)}
function statusOf(c){if(c.cancelled)return{key:'cancelados',label:'Cancelado',color:'gray'};if(c.lifetime)return{key:'ativos',label:'Vitalício',color:'green'};const days=diffDays(c.dueDate);if(days<0)return{key:'vencidos',label:'Vencido',color:'red'};if(days===0)return{key:'hoje',label:'Vence hoje',color:'amber'};if(days<=5)return{key:'proximos',label:`Vence em ${days} dia${days>1?'s':''}`,color:'amber'};return{key:'ativos',label:'Ativo',color:'green'}}
function escapeHTML(text=''){return String(text).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function parseStoredNotes(value,row){try{if(typeof value==='string'&&value.startsWith(DEVICE_MARKER)){const p=JSON.parse(value.slice(DEVICE_MARKER.length));return{notes:p.notes||'',devices:p.devices||[],resellerName:p.resellerName||'',resellerPhone:p.resellerPhone||'',cost:Number(p.cost)||0}}}catch{}return{notes:value||'',devices:[],resellerName:'',resellerPhone:'',cost:0}}
function toClient(row){const p=parseStoredNotes(row.notes,row);return{id:row.id,name:row.name,phone:row.phone,appName:row.app_name,startDate:row.start_date,plan:row.plan,value:Number(row.amount),cost:Number(row.cost??p.cost)||0,resellerId:row.reseller_id||null,resellerName:p.resellerName,resellerPhone:p.resellerPhone,payment:row.payment_method,notes:p.notes,devices:p.devices.length?p.devices:[{device:'TV 1',appName:row.app_name||'',mac:'',key:'',screens:Number(row.screens)||1}],dueDate:row.due_date,cancelled:row.cancelled,lifetime:!!row.lifetime,screens:Number(row.screens)||1,createdAt:row.created_at}}
function fromClient(d){return{name:d.name,phone:d.phone,app_name:d.devices[0]?.appName||'',start_date:d.startDate,plan:d.plan,amount:d.value,cost:Number(d.cost)||0,reseller_id:d.resellerId||null,payment_method:d.payment,notes:DEVICE_MARKER+JSON.stringify({notes:d.notes||'',devices:d.devices||[],resellerName:d.resellerName||'',resellerPhone:d.resellerPhone||'',cost:Number(d.cost)||0}),due_date:d.dueDate,cancelled:!!d.cancelled,lifetime:!!d.lifetime,screens:Number(d.screens)||1}}
function authHeaders(extra={}){return{'apikey':SUPABASE_KEY,'Authorization':`Bearer ${session?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json',...extra}}
async function api(path,options={}){const res=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:authHeaders(options.headers||{})});const text=await res.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!res.ok)throw new Error(data.msg||data.message||data.error_description||'Não foi possível concluir.');return data}
function storeSession(data){session=data;localStorage.setItem(SESSION_KEY,JSON.stringify(data))}
function clearSession(){session=null;localStorage.removeItem(SESSION_KEY)}
async function restoreSession(){try{const saved=JSON.parse(localStorage.getItem(SESSION_KEY));if(!saved?.refresh_token)return false;if(saved.expires_at&&saved.expires_at*1000>Date.now()+60000){session=saved;return true}const fresh=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:saved.refresh_token})});fresh.expires_at=Math.floor(Date.now()/1000)+fresh.expires_in;storeSession(fresh);return true}catch{clearSession();return false}}
async function loadData(){const [clientRows,renewalRows,resellerRows,apps]=await Promise.all([api('/rest/v1/clients?select=*&order=due_date.asc'),api('/rest/v1/renewals?select=*&order=created_at.desc'),api('/rest/v1/resellers?select=id,name,phone,notes&active=eq.true&order=name.asc'),api('/rest/v1/client_apps?select=*&active=eq.true&order=created_at.asc')]);resellers=resellerRows;const rm=new Map(resellers.map(r=>[r.id,r])),am=new Map();apps.forEach(a=>{const l=am.get(a.client_id)||[];l.push({device:a.device_name,appName:a.app_name,username:a.login_username||'',password:a.login_password||'',mac:a.mac||'',key:a.app_key||'',screens:Number(a.screens)||1,appPrice:a.app_price==null?'':Number(a.app_price)});am.set(a.client_id,l)});clients=clientRows.map(row=>{const c=toClient(row),r=rm.get(row.reseller_id);if(r){c.resellerId=r.id;c.resellerName=r.name;c.resellerPhone=r.phone||''}if(am.has(row.id))c.devices=am.get(row.id);return c});renewals=renewalRows;render()}
async function ensureReseller(name,phone){name=(name||'').trim();if(!name)return null;const rows=await api('/rest/v1/resellers?on_conflict=owner_id,name',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({name,phone:(phone||'').trim(),active:true})});return rows[0]?.id||null}
async function syncClientApps(id,d){await api('/rest/v1/client_apps?client_id=eq.'+encodeURIComponent(id),{method:'DELETE'});const rows=(d.devices||[]).filter(x=>x.appName).map(x=>({client_id:id,device_name:x.device||'Dispositivo',app_name:x.appName,login_username:x.username||'',login_password:x.password||'',mac:x.mac||'',app_key:x.key||'',screens:Number(x.screens)||1,app_price:x.appPrice===''?null:Number(x.appPrice),start_date:d.startDate,due_date:d.lifetime?null:d.dueDate,lifetime:!!d.lifetime,active:true}));if(rows.length)await api('/rest/v1/client_apps',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows)})}
async function init(){if(await restoreSession())await enterApp();else showLogin()}
function showLogin(){$('loginScreen').hidden=false;$('appShell').hidden=true}
async function enterApp(){$('loginScreen').hidden=true;$('appShell').hidden=false;$('connectedEmail').textContent='Conectado: admin';try{await loadData()}catch(e){clearSession();showLogin();$('loginError').textContent=e.message}}
function setBusy(busy){document.body.classList.toggle('loading',busy)}
function showToast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}

function render(){renderSummary();renderAnalytics();renderResellerDatalist();let list=clients.filter(matchesFilter).filter(c=>`${c.name} ${c.phone} ${(c.devices||[]).map(d=>d.appName).join(' ')}`.toLowerCase().includes($('searchInput').value.toLowerCase().trim()));const sort=$('sortSelect').value;list.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'pt-BR'):sort==='recent'?b.createdAt.localeCompare(a.createdAt):((a.dueDate||'9999').localeCompare(b.dueDate||'9999')));$('clientRows').innerHTML=list.map(clientRow).join('');$('emptyState').hidden=list.length!==0;document.querySelector('table').hidden=list.length===0;const titles={todos:'Todos os clientes',hoje:'Vencem hoje',amanha:'Vencem amanhã',proximos:'Próximos 5 dias',vencidos:'Clientes vencidos',ativos:'Clientes ativos',cancelados:'Clientes cancelados'};$('listTitle').textContent=titles[activeFilter];$('listSubtitle').textContent=`${list.length} cliente${list.length===1?'':'s'} encontrado${list.length===1?'':'s'}.`}
function matchesFilter(c){const s=statusOf(c),days=diffDays(c.dueDate);if(activeFilter==='todos')return true;if(activeFilter==='amanha')return !c.cancelled&&days===1;if(activeFilter==='proximos')return !c.cancelled&&days>=1&&days<=5;return s.key===activeFilter}
function renderSummary(){const valid=clients.filter(c=>!c.cancelled),now=today(),todayList=valid.filter(c=>diffDays(c.dueDate)===0),soon=valid.filter(c=>diffDays(c.dueDate)>=1&&diffDays(c.dueDate)<=5),overdue=valid.filter(c=>diffDays(c.dueDate)<0),active=valid.filter(c=>diffDays(c.dueDate)>=0),monthSales=clients.filter(c=>{const d=parseDate(c.startDate);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});$('countToday').textContent=todayList.length;$('valueToday').textContent=sum(todayList);$('countSoon').textContent=soon.length;$('valueSoon').textContent=sum(soon);$('countOverdue').textContent=overdue.length;$('valueOverdue').textContent=sum(overdue);$('countActive').textContent=active.length;$('monthRevenue').textContent=`${sum(monthSales)} no mês`}
function renderAnalytics(){const range=periodBounds(),previous=previousBounds(range),active=clients.filter(c=>!c.cancelled&&diffDays(c.dueDate)>=0),outside=clients.length-active.length,newNow=clients.filter(c=>inRange(c.startDate,range)),newPrevious=clients.filter(c=>inRange(c.startDate,previous)),expiring=active.filter(c=>diffDays(c.dueDate)>=0&&diffDays(c.dueDate)<=7),payments=renewals.filter(r=>['sale','renewal'].includes(r.event_type)),paymentsNow=payments.filter(r=>inRange(r.created_at,range)),paymentsPrevious=payments.filter(r=>inRange(r.created_at,previous)),revenue=paymentsNow.reduce((t,r)=>t+Number(r.amount||0),0),previousRevenue=paymentsPrevious.reduce((t,r)=>t+Number(r.amount||0),0),portfolio=active.reduce((t,c)=>t+c.value,0),mrr=active.reduce((t,c)=>t+(c.value/planMonths(c.plan)),0),risk=expiring.reduce((t,c)=>t+c.value,0),ticket=paymentsNow.length?revenue/paymentsNow.length:0,retention=clients.length?Math.round(active.length/clients.length*100):0;const labels={lastMonth:'Mês passado','30d':'Últimos 30 dias',month:'Mês atual',all:'Todo o período',custom:`${dateBR(formatISO(range.start))} até ${dateBR(formatISO(range.end))}`};$('periodLabel').textContent=labels[dashboardPeriod];$('metricActive').textContent=active.length;$('metricActiveValue').textContent=`${money(portfolio)} em planos ativos`;$('metricNew').textContent=newNow.length;$('metricNewTrend').textContent=trendText(newNow.length,newPrevious.length);$('metricExpiring').textContent=expiring.length;$('metricRisk').textContent=`${money(risk)} em risco`;$('metricRetention').textContent=`${retention}%`;$('metricChurn').textContent=`${outside} cliente${outside===1?'':'s'} fora da ativa`;$('metricRevenue').textContent=money(revenue);$('metricRevenueTrend').textContent=trendText(revenue,previousRevenue);$('metricMrr').textContent=money(mrr);$('metricTicket').textContent=money(ticket);$('metricSalesCount').textContent=`${paymentsNow.length} pagamento${paymentsNow.length===1?'':'s'} no período`;$('metricPortfolio').textContent=money(portfolio)}
function sum(list){return money(list.reduce((total,c)=>total+Number(c.value),0))}
function newDevice(name='TV 1'){return{device:name,appName:'',mac:'',key:'',screens:1}}
function appCode(name=''){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/^app\s*/,'').replace(/[^a-z0-9]/g,'')}
function appUsesMac(name=''){return !NO_MAC_APPS.has(appCode(name))}
function formatMac(value=''){const raw=value.toUpperCase().replace(/[^0-9A-F]/g,'').slice(0,12);return raw.match(/.{1,2}/g)?.join(':')||''}
function updateDeviceAccess(row){const usesMac=appUsesMac(row.querySelector('[data-device="appName"]').value);row.querySelectorAll('.mac-key-field').forEach(label=>label.hidden=!usesMac)}
function renderDevices(devices=[newDevice()]){const list=$('devicesList'),rows=devices.length?devices:[newDevice()];list.innerHTML=rows.map((d,i)=>`<div class="device-entry"><label>Dispositivo<input data-device="device" value="${escapeHTML(d.device||`TV ${i+1}`)}" placeholder="TV 1"></label><label>Aplicativo<input data-device="appName" list="apps" value="${escapeHTML(d.appName||'')}" placeholder="XCloud TV"></label><label>Usuário<input data-device="username" value="${escapeHTML(d.username||'')}" placeholder="Usuário do cliente"></label><label>Senha<input data-device="password" value="${escapeHTML(d.password||'')}" placeholder="Senha do cliente"></label><label class="mac-key-field">MAC<input data-device="mac" maxlength="17" value="${escapeHTML(formatMac(d.mac||''))}" placeholder="AA:BB:CC:11:22:33"></label><label class="mac-key-field">Key<input data-device="key" value="${escapeHTML(d.key||'')}" placeholder="123456789"></label><label>Valor pago no aplicativo (R$)<input data-device="appPrice" type="number" min="0" step="0.01" value="${d.appPrice==null?'':escapeHTML(d.appPrice)}" placeholder="Deixe vazio se for grátis"></label><label>Telas<select data-device="screens">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option value="${n}" ${Number(d.screens||1)===n?'selected':''}>${n}</option>`).join('')}</select></label><button type="button" class="remove-device">×</button></div>`).join('');list.querySelectorAll('.device-entry').forEach(row=>{const app=row.querySelector('[data-device="appName"]'),mac=row.querySelector('[data-device="mac"]');app.addEventListener('input',()=>updateDeviceAccess(row));app.addEventListener('change',()=>updateDeviceAccess(row));mac.addEventListener('input',()=>{mac.value=formatMac(mac.value)});updateDeviceAccess(row)});list.querySelectorAll('.remove-device').forEach(b=>b.onclick=()=>{if(list.children.length>1)b.parentElement.remove()})}
function getDevices(){return [...document.querySelectorAll('.device-entry')].map(r=>{const v=k=>r.querySelector(`[data-device="${k}"]`)?.value.trim()||'',appName=v('appName'),usesMac=appUsesMac(appName);return{device:v('device'),appName,username:v('username'),password:v('password'),mac:usesMac?v('mac'):'',key:usesMac?v('key'):'',appPrice:v('appPrice'),screens:Number(v('screens'))||1}}).filter(d=>d.appName||d.username||d.mac||d.key)}
function renderResellerDatalist(){$('resellerNames').innerHTML=resellers.map(r=>`<option value="${escapeHTML(r.name)}"></option>`).join('')}
function resellerMessage(name,group){const due=group.filter(c=>!c.cancelled&&!c.lifetime&&diffDays(c.dueDate)<=5);let t=`Olá, ${name}! Segue a cobrança dos seus clientes na JS Tech.\n\n`;if(!due.length)t+='Nenhum cliente vence nos próximos 5 dias.\n';due.forEach(c=>{t+=`Cliente: ${c.name}\nAplicativos:\n${(c.devices||[]).map(d=>`• ${d.device}: ${d.appName} · ${d.screens} tela${d.screens>1?'s':''}${d.appPrice!==''&&d.appPrice!=null?` · ${money(d.appPrice)}`:''}`).join('\n')}\nCadastro: ${dateBR(c.startDate)}\nVencimento: ${dateBR(c.dueDate)}\nValor do plano: ${money(c.value)}\nSituação: ${statusOf(c).label}\n\n`});return t+'JS Tech — conectado com você.'}
function renderResellers(){const q=$('resellerSearch').value.toLowerCase().trim(),groups={};resellers.forEach(r=>groups[r.name]=[]);clients.forEach(c=>{const n=c.resellerName||DIRECT_RESELLER;(groups[n]||(groups[n]=[])).push(c)});const valid=clients.filter(c=>!c.cancelled),revenue=valid.reduce((t,c)=>t+c.value,0),cost=valid.reduce((t,c)=>t+c.cost,0);$('generalRevenue').textContent=money(revenue);$('generalCost').textContent=money(cost);$('generalProfit').textContent=money(revenue-cost);$('generalResellers').textContent=resellers.length;const entries=Object.entries(groups).filter(([n,g])=>!q||n.toLowerCase().includes(q)||g.some(c=>c.name.toLowerCase().includes(q)));$('resellersEmpty').hidden=!!entries.length;$('resellersTree').innerHTML=entries.map(([n,g])=>{const rr=resellers.find(x=>x.name===n),a=g.filter(c=>!c.cancelled),r=a.reduce((t,c)=>t+c.value,0),ct=a.reduce((t,c)=>t+c.cost,0),phone=rr?.phone||g.find(c=>c.resellerPhone)?.resellerPhone||'',action=n===DIRECT_RESELLER?'':`${phone?`<a class="action-btn" target="_blank" href="https://wa.me/${whatsappNumber(phone)}?text=${encodeURIComponent(resellerMessage(n,g))}">Cobrar no WhatsApp</a>`:'<span class="badge gray">Sem WhatsApp</span>'}<button class="action-btn" onclick="openClientForReseller('${rr?.id||''}')">+ Cliente do revendedor</button>`;return `<section class="reseller-card"><div class="reseller-head"><div><h3>${escapeHTML(n)}</h3><p>${g.length} cliente(s) ${phone?'· '+escapeHTML(phone):''}</p></div><div class="reseller-totals"><div><span>Faturamento</span><strong>${money(r)}</strong></div><div><span>Apps pagos</span><strong>${money(ct)}</strong></div><div><span>Lucro</span><strong class="positive">${money(r-ct)}</strong></div>${action}</div></div>${g.length?g.map(c=>`<div class="reseller-client"><div><strong>${escapeHTML(c.name)}</strong><small>${escapeHTML(c.phone)}</small></div><div>${(c.devices||[]).map(d=>`${escapeHTML(d.device)}: ${escapeHTML(d.appName)} · ${d.screens} tela(s)${d.appPrice!==''&&d.appPrice!=null?` · ${money(d.appPrice)}`:''}`).join('<br>')}<small>${dateBR(c.startDate)} → ${c.lifetime?'Vitalício':dateBR(c.dueDate)}</small></div><div>Venda<br><strong>${money(c.value)}</strong></div><div>Apps pagos<br><strong>${money(c.cost)}</strong></div><div class="positive">Lucro<br><strong>${money(c.value-c.cost)}</strong></div><span class="badge ${statusOf(c).color}">${statusOf(c).label}</span></div>`).join(''):'<div class="reseller-empty-row">Nenhum cliente. Clique em “Cliente do revendedor”.</div>'}</section>`}).join('')}
async function loadAndroidApps(){try{androidApps=await api('/rest/v1/android_apps?select=id,name,price&active=eq.true&order=name.asc')}catch{androidApps=[]}$('androidAppsGrid').innerHTML=androidApps.map(a=>`<article class="android-app-card"><strong>${escapeHTML(a.name)}</strong><span>Aplicativo Android</span><label>Valor padrão (opcional)<input class="android-price" data-app-id="${a.id}" type="number" min="0" step="0.01" value="${a.price==null?'':a.price}" placeholder="Em branco"><button class="ghost small" onclick="saveAndroidPrice('${a.id}')">Salvar valor</button></label></article>`).join('');$('apps').innerHTML=androidApps.map(a=>`<option>${escapeHTML(a.name)}</option>`).join('')}
async function saveAndroidPrice(id){const input=document.querySelector(`[data-app-id="${id}"]`),price=input.value===''?null:Number(input.value);try{await api(`/rest/v1/android_apps?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({price})});showToast('Valor do aplicativo salvo.')}catch(e){alert(e.message)}}
async function saveAndroidApp(){const name=$('newAndroidAppName').value.trim(),price=$('newAndroidAppPrice').value===''?null:Number($('newAndroidAppPrice').value);if(!name){alert('Digite o nome do aplicativo.');return}try{await api('/rest/v1/android_apps?on_conflict=owner_id,name',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({name,price,active:true})});$('newAndroidAppName').value='';$('newAndroidAppPrice').value='';await loadAndroidApps();showToast('Aplicativo cadastrado.')}catch(e){alert(e.message)}}
function setPanelView(view){const apps=view==='apps',resellers=view==='resellers',special=apps||resellers;document.querySelector('.topbar').hidden=special;document.querySelector('.analytics').hidden=special;document.querySelector('.summary-grid').hidden=special;document.querySelector('.panel:not(#resellersSection):not(#androidAppsSection)').hidden=special;$('resellersSection').hidden=!resellers;$('androidAppsSection').hidden=!apps;if(resellers)renderResellers();if(apps)loadAndroidApps()}
function clientRow(c){const s=statusOf(c),days=c.lifetime?999:diffDays(c.dueDate),hint=c.lifetime?'Sem vencimento':days<0?`${Math.abs(days)} dia${Math.abs(days)>1?'s':''} atrasado`:days===0?'É hoje':days===1?'Amanhã':`Faltam ${days} dias`;return `<tr><td class="client-name"><strong>${escapeHTML(c.name)}</strong><span>${escapeHTML(c.phone)}</span></td><td>${escapeHTML((c.devices||[]).map(d=>d.appName).join(', '))}</td><td>${c.lifetime?'Vitalício':planLabel(c.plan)} · ${c.screens} tela(s)</td><td class="date-cell"><strong>${c.lifetime?'Vitalício':dateBR(c.dueDate)}</strong><span>${c.cancelled?'Sem renovação':hint}</span></td><td><strong>${money(c.value)}</strong></td><td><span class="badge ${s.color}">${s.label}</span></td><td><div class="actions">${c.lifetime?'':`<button class="action-btn renew" onclick="renewClient('${c.id}')">Renovar</button>`}<button class="action-btn" onclick="sendCharge('${c.id}')">WhatsApp</button><button class="action-btn" onclick="showClientData('${c.id}')">Ver dados</button><details class="more"><summary class="action-btn">•••</summary><div class="more-menu"><button onclick="editClient('${c.id}')">Editar</button><button onclick="showHistory('${c.id}')">Histórico</button><button onclick="toggleCancel('${c.id}')">${c.cancelled?'Reativar':'Cancelar'}</button><button class="danger" onclick="deleteClient('${c.id}')">Excluir</button></div></details></div></td></tr>`}
function openForm(c=null){$('clientForm').reset();$('clientId').value=c?.id||'';$('formTitle').textContent=c?'Editar cliente':'Novo cliente';$('startDate').value=c?.startDate||isoToday();$('plan').value=c?.plan||'30d';$('screens').value=String(c?.screens||1);$('lifetime').checked=!!c?.lifetime;renderDevices(c?.devices||[newDevice()]);if(c){$('name').value=c.name;$('phone').value=c.phone;$('value').value=c.value;$('resellerName').value=c.resellerName||'';$('resellerPhone').value=c.resellerPhone||'';$('payment').value=c.payment;$('notes').value=c.notes||''}updatePreview();$('clientDialog').showModal()}
function openClientForReseller(id){const r=resellers.find(x=>x.id===id);openForm();if(r){$('resellerName').value=r.name;$('resellerPhone').value=r.phone||''}}
function updatePreview(){const lifetime=$('lifetime').checked;$('plan').disabled=lifetime;$('datePreview').textContent=lifetime?'Vitalício — sem vencimento':$('startDate').value?dateBR(calculateDue($('startDate').value,$('plan').value)):'—'}
function deviceDataText(d,i){const access=appUsesMac(d.appName)?`\nMAC: ${d.mac||'—'}\nKey: ${d.key||'—'}`:'';return `${d.device||`Aparelho ${i+1}`}\nAplicativo Android: ${d.appName||'—'}\nUsuário: ${d.username||'—'}\nSenha: ${d.password||'—'}${access}\nTelas: ${d.screens||1}\nValor do aplicativo: ${d.appPrice!==''&&d.appPrice!=null?money(d.appPrice):'Grátis / não informado'}`}
function showClientData(id){const c=clients.find(x=>x.id===id);if(!c)return;clientDataId=id;const devices=c.devices||[];clientDataText=`Cliente: ${c.name}\nWhatsApp: ${c.phone}\nPlano: ${c.lifetime?'Vitalício':planLabel(c.plan)}\nCadastro: ${dateBR(c.startDate)}\nVencimento: ${c.lifetime?'Sem vencimento':dateBR(c.dueDate)}\nValor: ${money(c.value)}\nRevendedor: ${c.resellerName||'Cliente direto'}\n\n`+devices.map(deviceDataText).join('\n\n');$('clientDataTitle').textContent=c.name;$('clientDataContent').innerHTML=`<div class="data-summary"><div><span>WhatsApp</span><strong>${escapeHTML(c.phone)}</strong></div><div><span>Plano</span><strong>${c.lifetime?'Vitalício':escapeHTML(planLabel(c.plan))}</strong></div><div><span>Vencimento</span><strong>${c.lifetime?'Sem vencimento':dateBR(c.dueDate)}</strong></div><div><span>Responsável</span><strong>${escapeHTML(c.resellerName||'Cliente direto')}</strong></div></div>`+devices.map((d,i)=>{const macKey=appUsesMac(d.appName)?`<div><span>MAC</span><strong>${escapeHTML(d.mac||'—')}</strong></div><div><span>Key</span><strong>${escapeHTML(d.key||'—')}</strong></div>`:'';return `<section class="data-device"><div class="data-device-head"><div><span>${escapeHTML(d.device||`Aparelho ${i+1}`)}</span><h3>${escapeHTML(d.appName||'Aplicativo não informado')}</h3></div><b>Aplicativo Android</b></div><div class="data-fields"><div><span>Usuário</span><strong>${escapeHTML(d.username||'—')}</strong></div><div><span>Senha</span><strong>${escapeHTML(d.password||'—')}</strong></div>${macKey}<div><span>Telas</span><strong>${d.screens||1}</strong></div><div><span>Valor do aplicativo</span><strong>${d.appPrice!==''&&d.appPrice!=null?money(d.appPrice):'Grátis / não informado'}</strong></div></div></section>`}).join('');$('moveClientReseller').innerHTML=`<option value="">Cliente direto</option>`+resellers.map(r=>`<option value="${r.id}" ${c.resellerId===r.id?'selected':''}>${escapeHTML(r.name)}</option>`).join('');$('clientDataDialog').showModal()}
async function moveClientToReseller(){const c=clients.find(x=>x.id===clientDataId);if(!c)return;const id=$('moveClientReseller').value,r=resellers.find(x=>x.id===id);try{setBusy(true);c.resellerId=id||null;c.resellerName=r?.name||'';c.resellerPhone=r?.phone||'';await api(`/rest/v1/clients?id=eq.${c.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({reseller_id:c.resellerId,notes:fromClient(c).notes})});await addHistory(c,'update',c.dueDate,c.dueDate,`Cliente movido para ${c.resellerName||'Cliente direto'}`);$('clientDataDialog').close();render();showToast(`Cliente movido para ${c.resellerName||'Cliente direto'}.`)}catch(e){alert(e.message)}finally{setBusy(false)}}
function editClient(id){openForm(clients.find(c=>c.id===id))}
async function addHistory(c,type,oldDue,newDue,description,amount=0){const rows=await api('/rest/v1/renewals',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({client_id:c.id,event_type:type,plan:c.plan,amount,previous_due_date:oldDue,new_due_date:newDue,description})});if(rows[0])renewals.unshift(rows[0]);return rows[0]}
async function renewClient(id){const c=clients.find(c=>c.id===id);if(!c)return;const base=diffDays(c.dueDate)>=0?c.dueDate:isoToday(),oldDue=c.dueDate,newDue=calculateDue(base,c.plan);try{setBusy(true);await api(`/rest/v1/clients?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({due_date:newDue,cancelled:false})});await addHistory(c,'renewal',oldDue,newDue,`Renovado por ${planLabel(c.plan)}`,c.value);c.dueDate=newDue;c.cancelled=false;c.lastRenewedAt=isoToday();render();showToast(`Renovação de ${c.name} registrada.`);showMessage(c,'renewal')}catch(e){alert(e.message)}finally{setBusy(false)}}
async function toggleCancel(id){const c=clients.find(c=>c.id===id);if(!c)return;try{setBusy(true);const cancelled=!c.cancelled;await api(`/rest/v1/clients?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({cancelled})});await addHistory(c,cancelled?'cancel':'reactivate',c.dueDate,c.dueDate,cancelled?'Cliente cancelado':'Cliente reativado');c.cancelled=cancelled;render()}catch(e){alert(e.message)}finally{setBusy(false)}}
async function deleteClient(id){const c=clients.find(c=>c.id===id);if(!c||!confirm(`Excluir definitivamente o cadastro de ${c.name}?`))return;try{setBusy(true);await api(`/rest/v1/clients?id=eq.${id}`,{method:'DELETE'});clients=clients.filter(x=>x.id!==id);renewals=renewals.filter(x=>x.client_id!==id);render();showToast('Cliente excluído.')}catch(e){alert(e.message)}finally{setBusy(false)}}
async function showHistory(id){const c=clients.find(c=>c.id===id);if(!c)return;try{const rows=await api(`/rest/v1/renewals?client_id=eq.${id}&select=*&order=created_at.desc`);$('historyTitle').textContent=c.name;$('historyContent').innerHTML=rows.map(h=>`<div class="history-item"><strong>${escapeHTML(h.description)}</strong><span>${dateBR(h.created_at.slice(0,10))}${Number(h.amount)?` · ${money(h.amount)}`:''}</span></div>`).join('')||'<p>Nenhum registro encontrado.</p>';$('historyDialog').showModal()}catch(e){alert(e.message)}}
function activationMessage(c,renewal=false){const access=(c.devices||[]).map((d,i)=>`\n${d.device||`Aparelho ${i+1}`}\nAplicativo: ${d.appName||'—'}\nUsuário: ${d.username||'—'}\nSenha: ${d.password||'—'}\nMAC: ${d.mac||'—'}\nKey: ${d.key||'—'}`).join('\n');return `Olá, ${c.name}! Seu pacote de ${c.lifetime?'Vitalício':planLabel(c.plan)} foi ${renewal?'renovado':'ativado'} com sucesso.\n${access}\n\nData da ${renewal?'renovação':'contratação'}: ${dateBR(renewal?(c.lastRenewedAt||isoToday()):c.startDate)}\nVencimento: ${c.lifetime?'Sem vencimento':dateBR(c.dueDate)}\n\nAgradecemos pela preferência!\nJS Tech — conectado com você.`}
function chargeMessage(c){return `Olá, ${c.name}! Tudo bem? Passando para avisar que seu plano de ${planLabel(c.plan)} ${diffDays(c.dueDate)<0?`venceu em ${dateBR(c.dueDate)}`:`vence em ${dateBR(c.dueDate)}`}. O valor para renovação é ${money(c.value)}.\n\nSe desejar continuar, fale comigo por aqui.\nJS Tech — conectado com você.`}
function showMessage(c,type){messageClientId=c.id;$('messageTitle').textContent=type==='charge'?'Aviso de vencimento':type==='renewal'?'Renovação realizada':'Ativação realizada';$('messageText').value=type==='charge'?chargeMessage(c):activationMessage(c,type==='renewal');$('messageDialog').showModal()}
function sendCharge(id){const c=clients.find(c=>c.id===id);if(c)showMessage(c,'charge')}
function whatsappNumber(phone){let n=phone.replace(/\D/g,'');if(n.length===10||n.length===11)n='55'+n;return n}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').style.color='';$('loginError').textContent='';const username=$('loginUser').value.trim().toLowerCase(),password=$('loginPassword').value;if(username!==ADMIN_USER){$('loginError').textContent='Usuário ou senha incorretos.';return}try{setBusy(true);let data;try{data=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:ADMIN_EMAIL,password})})}catch{const redirect=encodeURIComponent(location.origin);data=await api(`/auth/v1/signup?redirect_to=${redirect}`,{method:'POST',body:JSON.stringify({email:ADMIN_EMAIL,password})});if(!data.access_token){$('loginError').style.color='#43d99c';$('loginError').textContent='Primeiro acesso criado. Confirme o e-mail enviado para juliosirlene43@gmail.com e depois clique em Entrar.';return}}data.expires_at=Math.floor(Date.now()/1000)+data.expires_in;storeSession(data);await enterApp()}catch(e){$('loginError').style.color='';$('loginError').textContent='Não foi possível entrar. Confira o usuário e a senha.'}finally{setBusy(false)}});
$('logoutBtn').addEventListener('click',async()=>{try{await api('/auth/v1/logout',{method:'POST'})}catch{}clearSession();clients=[];renewals=[];showLogin()});
$('clientForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('clientId').value,existing=clients.find(c=>c.id===id),oldDue=existing?.dueDate||null,lifetime=$('lifetime').checked,devices=getDevices(),appCost=devices.reduce((total,d)=>total+(d.appPrice===''?0:Number(d.appPrice)||0),0),data={name:$('name').value.trim(),phone:$('phone').value.trim(),devices,startDate:$('startDate').value,plan:$('plan').value,value:Number($('value').value),cost:appCost,resellerName:$('resellerName').value.trim(),resellerPhone:$('resellerPhone').value.trim(),payment:$('payment').value,notes:$('notes').value.trim(),screens:Number($('screens').value)||1,lifetime,cancelled:existing?.cancelled||false};data.dueDate=lifetime?(existing?.dueDate||calculateDue(data.startDate,data.plan)):calculateDue(data.startDate,data.plan);try{setBusy(true);data.resellerId=await ensureReseller(data.resellerName,data.resellerPhone);if(existing){await api(`/rest/v1/clients?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(fromClient(data))});await syncClientApps(id,data);Object.assign(existing,data);await addHistory(existing,'update',oldDue,data.dueDate,`Cadastro atualizado${lifetime?' · Vitalício':''}`);$('clientDialog').close();render();showToast('Cadastro atualizado.')}else{const rows=await api('/rest/v1/clients',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(fromClient(data))});const c=toClient(rows[0]);await syncClientApps(c.id,data);Object.assign(c,data);clients.push(c);await addHistory(c,'sale',null,c.dueDate,`Venda cadastrada: ${lifetime?'Vitalício':planLabel(c.plan)}`,c.value);$('clientDialog').close();render();showMessage(c,'activation')}}catch(e){alert(e.message)}finally{setBusy(false)}});
document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>$('clientDialog').close()));document.querySelectorAll('.close-message').forEach(b=>b.addEventListener('click',()=>$('messageDialog').close()));document.querySelectorAll('.close-history').forEach(b=>b.addEventListener('click',()=>$('historyDialog').close()));
document.querySelectorAll('.close-client-data').forEach(b=>b.addEventListener('click',()=>$('clientDataDialog').close()));$('copyClientDataBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(clientDataText);showToast('Dados do cliente copiados.')});
$('moveClientBtn').addEventListener('click',moveClientToReseller);
document.querySelectorAll('.close-reseller').forEach(b=>b.addEventListener('click',()=>$('resellerDialog').close()));
$('newResellerBtn').addEventListener('click',()=>{$('resellerForm').reset();$('resellerDialog').showModal()});
$('resellerForm').addEventListener('submit',async e=>{e.preventDefault();try{setBusy(true);await api('/rest/v1/resellers?on_conflict=owner_id,name',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({name:$('newResellerName').value.trim(),phone:$('newResellerPhone').value.trim(),notes:$('newResellerNotes').value.trim(),active:true})});$('resellerDialog').close();await loadData();setPanelView('resellers');showToast('Revendedor cadastrado. Agora adicione os clientes dele.')}catch(e){alert(e.message)}finally{setBusy(false)}});
$('newClientBtn').addEventListener('click',()=>openForm());$('addDeviceBtn').addEventListener('click',()=>{const d=getDevices();d.push(newDevice(`TV ${d.length+1}`));renderDevices(d)});$('emptyAddBtn').addEventListener('click',()=>openForm());$('startDate').addEventListener('change',updatePreview);$('plan').addEventListener('change',updatePreview);$('lifetime').addEventListener('change',updatePreview);$('searchInput').addEventListener('input',render);$('sortSelect').addEventListener('change',render);$('resellerSearch').addEventListener('input',renderResellers);$('saveAndroidAppBtn').addEventListener('click',saveAndroidApp);
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.view){setPanelView(b.dataset.view);return}setPanelView('clients');activeFilter=b.dataset.filter;render()}));
document.querySelectorAll('.period-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.period-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');dashboardPeriod=b.dataset.period;$('customDates').hidden=dashboardPeriod!=='custom';renderAnalytics()}));
$('applyPeriod').addEventListener('click',renderAnalytics);
$('copyMessageBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText($('messageText').value);showToast('Mensagem copiada.')});$('openWhatsappBtn').addEventListener('click',()=>{const c=clients.find(c=>c.id===messageClientId);if(c)window.open(`https://wa.me/${whatsappNumber(c.phone)}?text=${encodeURIComponent($('messageText').value)}`,'_blank','noopener')});
$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),clients},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-js-tech-${isoToday()}.json`;a.click();URL.revokeObjectURL(a.href);showToast('Backup baixado.')});
$('importInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.clients))throw new Error();if(confirm(`Importar ${data.clients.length} cliente(s) para o banco?`)){setBusy(true);for(const item of data.clients){const rows=await api('/rest/v1/clients',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(fromClient(item))});if(rows[0])await addHistory(toClient(rows[0]),'sale',null,rows[0].due_date,'Venda importada',Number(rows[0].amount||0))}await loadData();showToast('Backup importado.')}}catch{alert('Este arquivo de backup não é válido ou não pôde ser importado.')}finally{setBusy(false);e.target.value=''}});
$('todayText').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());
$('periodStart').value=formatISO(new Date(today().getFullYear(),today().getMonth(),1));$('periodEnd').value=isoToday();
function renderMonthlyReport(){const months=[];const now=today();for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;const sales=renewals.filter(r=>['sale','renewal'].includes(r.event_type)&&String(r.created_at||'').slice(0,7)===key),fallback=clients.filter(c=>String(c.startDate||'').slice(0,7)===key),rows=sales.length?sales:fallback.map(c=>({amount:c.value})),total=rows.reduce((sum,r)=>sum+Number(r.amount||0),0);months.push({label:new Intl.DateTimeFormat('pt-BR',{month:'short',year:'numeric'}).format(d),count:rows.length,total})}const max=Math.max(...months.map(m=>m.total),1);$('monthlyReport').innerHTML=months.map(m=>`<article class="month-card"><div><span>${m.label}</span><strong>${money(m.total)}</strong></div><small>${m.count} venda${m.count===1?'':'s'}/renovaç${m.count===1?'ão':'ões'}</small><div class="month-bar"><i style="width:${Math.round(m.total/max*100)}%"></i></div></article>`).join('')}
const originalRender=render;render=()=>{originalRender();renderMonthlyReport()};
init();
