const SUPABASE_URL='https://yifgptxujimzsjoeghte.supabase.co';
const SUPABASE_KEY='sb_publishable_TGA26mIiNQ686GJrvQI3aw_PmfP8V1-';
const ADMIN_EMAIL='juliosirlene43@gmail.com';
const ADMIN_USER='admin';
const SESSION_KEY='jstech_supabase_session';
let session=null,clients=[],renewals=[],resellers=[],activeFilter='todos',dashboardPeriod='30d',messageClientId=null,clientDataId=null,androidApps=[];
const DEVICE_MARKER='__JSTECH_DEVICES__',DIRECT_RESELLER='Cliente direto';let clientDataText='';
const NO_MAC_APPS=new Set(['jjplayer','duotv','multbox','sync21player','upplay','max21','xciptvplayer','dunaxpt','touroboxmod','touroboxt7v5','xplus70','youcinemod','touroboxv2','unirevenda','gpcpro','clouddy']);
const $=id=>document.getElementById(id);
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
const dateBR=date=>date?new Intl.DateTimeFormat('pt-BR').format(parseDate(date)):'—';
const today=()=>{const d=new Date();d.setHours(0,0,0,0);return d};
const isoToday=()=>formatISO(today());
function parseDate(value){const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)}
function formatISO(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function shiftDays(date,days){const d=new Date(date);d.setDate(d.getDate()+days);return d}
function periodBounds(type=dashboardPeriod){const now=today();let start,end=new Date(now);if(type==='lastMonth'){start=new Date(now.getFullYear(),now.getMonth()-1,1);end=new Date(now.getFullYear(),now.getMonth(),0)}else if(type==='month'){start=new Date(now.getFullYear(),now.getMonth(),1)}else if(type==='all'){start=new Date(2000,0,1)}else if(type==='custom'){start=$('periodStart').value?parseDate($('periodStart').value):new Date(now.getFullYear(),now.getMonth(),1);end=$('periodEnd').value?parseDate($('periodEnd').value):now}else{start=shiftDays(now,-29)}return{start,end}}
function inRange(value,range){if(!value)return false;const d=parseDate(String(value).slice(0,10));return d>=range.start&&d<=range.end}
function previousBounds(range){const days=Math.round((range.end-range.start)/86400000)+1;return{start:shiftDays(range.start,-days),end:shiftDays(range.start,-1)}}
function planMonths(plan){return({'30d':1,'3m':3,'6m':6,'1y':12})[plan]||1}
function trendText(current,previous){if(!previous)return current?'Primeiro resultado neste comparativo':'Sem movimentação anterior';const pct=Math.round(((current-previous)/previous)*100);return `${pct>=0?'+':''}${pct}% vs. período anterior`}
function diffDays(date){return Math.round((parseDate(date)-today())/86400000)}
function planLabel(plan){return ({'30d':'30 dias','3m':'3 meses','6m':'6 meses','1y':'1 ano'})[plan]||plan}
function addMonths(date,months){const day=date.getDate();date.setDate(1);date.setMonth(date.getMonth()+months);const last=new Date(date.getFullYear(),date.getMonth()+1,0).getDate();date.setDate(Math.min(day,last))}
function calculateDue(start,plan){const d=parseDate(start);if(plan==='30d')d.setDate(d.getDate()+30);if(plan==='3m')addMonths(d,3);if(plan==='6m')addMonths(d,6);if(plan==='1y')addMonths(d,12);return formatISO(d)}
function statusOf(c){if(c.cancelled)return{key:'cancelados',label:'Cancelado',color:'gray'};if(c.lifetime)return{key:'ativos',label:'Vitalício',color:'green'};const days=diffDays(c.dueDate);if(days<0)return{key:'vencidos',label:'Vencido',color:'red'};if(days===0)return{key:'hoje',label:'Vence hoje',color:'amber'};if(days<=5)return{key:'proximos',label:`Vence em ${days} dia${days>1?'s':''}`,color:'amber'};return{key:'ativos',label:'Ativo',color:'green'}}
function escapeHTML(text=''){return String(text).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function parseStoredNotes(value,row){try{if(typeof value==='string'&&value.startsWith(DEVICE_MARKER)){const p=JSON.parse(value.slice(DEVICE_MARKER.length));return{notes:p.notes||'',devices:p.devices||[],resellerName:p.resellerName||'',resellerPhone:p.resellerPhone||'',cost:Number(p.cost)||0}}}catch{}return{notes:value||'',devices:[],resellerName:'',resellerPhone:'',cost:0}}
function toClient(row){const p=parseStoredNotes(row.notes,row);return{id:row.id,name:row.name,phone:row.phone,appName:row.app_name,startDate:row.start_date,plan:row.plan,value:Number(row.amount),cost:Number(row.cost??p.cost)||0,resellerId:row.reseller_id||null,resellerName:p.resellerName,resellerPhone:p.resellerPhone,payment:row.payment_method,notes:p.notes,devices:p.devices.length?p.devices:[{device:'TV 1',appName:row.app_name||'',mac:'',key:'',screens:Number(row.screens)||1}],dueDate:row.due_date,cancelled:row.cancelled,lifetime:!!row.lifetime,screens:Number(row.screens)||1,createdAt:row.created_at}}
function fromClient(d){return{name:d.name,phone:d.phone,app_name:d.devices[0]?.appName||'',start_date:d.startDate,plan:d.plan,amount:d.value,cost:Number(d.cost)||0,reseller_id:d.resellerId||null,payment_method:d.payment,notes:DEVICE_MARKER+JSON.stringify({notes:d.notes||'',devices:d.devices||[],resellerName:d.resellerName||'',resellerPhone:d.resellerPhone||'',cost:Number(d.cost)||0}),due_date:d.dueDate,cancelled:!!d.cancelled,lifetime:!!d.lifetime,screens:Number(d.screens)||1}}
function authHeaders(extra={}){return{'apikey':SUPABASE_KEY,'Authorization':`Bearer ${session?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json',...extra}}
async function api(path,options={}){const res=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:authHeaders(options.headers||{})});const text=await res.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!res.ok)throw new Error(data.error||data.msg||data.message||data.error_description||'Não foi possível concluir.');return data}
function storeSession(data){session=data;localStorage.setItem(SESSION_KEY,JSON.stringify(data))}
function clearSession(){session=null;localStorage.removeItem(SESSION_KEY)}
async function restoreSession(){try{const saved=JSON.parse(localStorage.getItem(SESSION_KEY));if(!saved?.refresh_token)return false;if(saved.expires_at&&saved.expires_at*1000>Date.now()+60000){session=saved;return true}const fresh=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:saved.refresh_token})});fresh.expires_at=Math.floor(Date.now()/1000)+fresh.expires_in;storeSession(fresh);return true}catch{clearSession();return false}}
async function loadData(){const [clientRows,renewalRows,resellerRows,apps]=await Promise.all([api('/rest/v1/clients?select=*&order=due_date.asc'),api('/rest/v1/renewals?select=*&order=created_at.desc'),api('/rest/v1/resellers?select=id,name,phone,notes&active=eq.true&order=name.asc'),api('/rest/v1/client_apps?select=*&active=eq.true&order=created_at.asc')]);resellers=resellerRows;const rm=new Map(resellers.map(r=>[r.id,r])),am=new Map();apps.forEach(a=>{const l=am.get(a.client_id)||[];l.push({device:a.device_name,appName:a.app_name,email:a.login_email||'',username:a.login_username||'',password:a.login_password||'',mac:a.mac||'',key:a.app_key||'',screens:Number(a.screens)||1,appPrice:a.app_price==null?'':Number(a.app_price)});am.set(a.client_id,l)});clients=clientRows.map(row=>{const c=toClient(row),r=rm.get(row.reseller_id);if(r){c.resellerId=r.id;c.resellerName=r.name;c.resellerPhone=r.phone||''}if(am.has(row.id))c.devices=am.get(row.id);return c});renewals=renewalRows;render()}
async function ensureReseller(name,phone){name=(name||'').trim();if(!name)return null;const rows=await api('/rest/v1/resellers?on_conflict=owner_id,name',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({name,phone:(phone||'').trim(),active:true})});return rows[0]?.id||null}
async function syncClientApps(id,d){await api('/rest/v1/client_apps?client_id=eq.'+encodeURIComponent(id),{method:'DELETE'});const rows=(d.devices||[]).filter(x=>x.appName).map(x=>({client_id:id,device_name:x.device||'Dispositivo',app_name:x.appName,login_email:x.email||'',login_username:x.username||'',login_password:x.password||'',mac:x.mac||'',app_key:x.key||'',screens:Number(x.screens)||1,app_price:x.appPrice===''?null:Number(x.appPrice),start_date:d.startDate,due_date:d.lifetime?null:d.dueDate,lifetime:!!d.lifetime,active:true}));if(rows.length)await api('/rest/v1/client_apps',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows)})}
async function init(){if(await restoreSession())await enterApp();else showLogin()}
function showLogin(){$('loginScreen').hidden=false;$('appShell').hidden=true}
async function enterApp(){$('loginScreen').hidden=true;$('appShell').hidden=false;$('connectedEmail').textContent='Conectado: admin';try{await loadData()}catch(e){clearSession();showLogin();$('loginError').textContent=e.message}}
function setBusy(busy){document.body.classList.toggle('loading',busy)}
function showToast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}

function render(){renderSummary();renderAnalytics();renderResellerDatalist();let list=clients.filter(matchesFilter).filter(c=>`${c.name} ${c.phone} ${(c.devices||[]).map(d=>d.appName).join(' ')}`.toLowerCase().includes($('searchInput').value.toLowerCase().trim()));const sort=$('sortSelect').value;list.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'pt-BR'):sort==='recent'?b.createdAt.localeCompare(a.createdAt):((a.dueDate||'9999').localeCompare(b.dueDate||'9999')));$('clientRows').innerHTML=list.map(clientRow).join('');$('emptyState').hidden=list.length!==0;document.querySelector('table').hidden=list.length===0;const titles={todos:'Todos os clientes',hoje:'Vencem hoje',amanha:'Vencem amanhã',proximos:'Próximos 5 dias',vencidos:'Clientes vencidos',ativos:'Clientes ativos',cancelados:'Clientes cancelados'};$('listTitle').textContent=titles[activeFilter];$('listSubtitle').textContent=`${list.length} cliente${list.length===1?'':'s'} encontrado${list.length===1?'':'s'}.`}
function matchesFilter(c){const s=statusOf(c),days=diffDays(c.dueDate);if(activeFilter==='todos')return true;if(activeFilter==='amanha')return !c.cancelled&&days===1;if(activeFilter==='proximos')return !c.cancelled&&days>=1&&days<=5;return s.key===activeFilter}
function renderSummary(){const valid=clients.filter(c=>!c.cancelled),now=today(),todayList=valid.filter(c=>diffDays(c.dueDate)===0),soon=valid.filter(c=>diffDays(c.dueDate)>=1&&diffDays(c.dueDate)<=5),overdue=valid.filter(c=>diffDays(c.dueDate)<0),active=valid.filter(c=>diffDays(c.dueDate)>=0),monthSales=clients.filter(c=>{const d=parseDate(c.startDate);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});$('countToday').textContent=todayList.length;$('valueToday').textContent=sum(todayList);$('countSoon').textContent=soon.length;$('valueSoon').textContent=sum(soon);$('countOverdue').textContent=overdue.length;$('valueOverdue').textContent=sum(overdue);$('countActive').textContent=active.length;$('monthRevenue').textContent=`${sum(monthSales)} no mês`}
function renderAnalytics(){const range=periodBounds(),previous=previousBounds(range),active=clients.filter(c=>!c.cancelled&&diffDays(c.dueDate)>=0),outside=clients.length-active.length,newNow=clients.filter(c=>inRange(c.startDate,range)),newPrevious=clients.filter(c=>inRange(c.startDate,previous)),expiring=active.filter(c=>diffDays(c.dueDate)>=0&&diffDays(c.dueDate)<=7),payments=renewals.filter(r=>['sale','renewal'].includes(r.event_type)),paymentsNow=payments.filter(r=>inRange(r.created_at,range)),paymentsPrevious=payments.filter(r=>inRange(r.created_at,previous)),revenue=paymentsNow.reduce((t,r)=>t+Number(r.amount||0),0),previousRevenue=paymentsPrevious.reduce((t,r)=>t+Number(r.amount||0),0),portfolio=active.reduce((t,c)=>t+c.value,0),mrr=active.reduce((t,c)=>t+(c.value/planMonths(c.plan)),0),risk=expiring.reduce((t,c)=>t+c.value,0),ticket=paymentsNow.length?revenue/paymentsNow.length:0,retention=clients.length?Math.round(active.length/clients.length*100):0;const labels={lastMonth:'Mês passado','30d':'Últimos 30 dias',month:'Mês atual',all:'Todo o período',custom:`${dateBR(formatISO(range.start))} até ${dateBR(formatISO(range.end))}`};$('periodLabel').textContent=labels[dashboardPeriod];$('metricActive').textContent=active.length;$('metricActiveValue').textContent=`${money(portfolio)} em planos ativos`;$('metricNew').textContent=newNow.length;$('metricNewTrend').textContent=trendText(newNow.length,newPrevious.length);$('metricExpiring').textContent=expiring.length;$('metricRisk').textContent=`${money(risk)} em risco`;$('metricRetention').textContent=`${retention}%`;$('metricChurn').textContent=`${outside} cliente${outside===1?'':'s'} fora da ativa`;$('metricRevenue').textContent=money(revenue);$('metricRevenueTrend').textContent=trendText(revenue,previousRevenue);$('metricMrr').textContent=money(mrr);$('metricTicket').textContent=money(ticket);$('metricSalesCount').textContent=`${paymentsNow.length} pagamento${paymentsNow.length===1?'':'s'} no período`;$('metricPortfolio').textContent=money(portfolio)}
function sum(list){return money(list.reduce((total,c)=>total+Number(c.value),0))}
function newDevice(name='TV 1'){return{device:name,appName:'',mac:'',key:'',screens:1}}
function appCode(name=''){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/^app\s*/,'').replace(/[^a-z0-9]/g,'')}
function appUsesMac(name=''){return !NO_MAC_APPS.has(appCode(name))}
function formatMac(value=''){const raw=value.toUpperCase().replace(/[^0-9A-F]/g,'').slice(0,12);return raw.match(/.{1,2}/g)?.join(':')||''}
function updateDeviceAccess(row){const appName=row.querySelector('[data-device="appName"]').value,isClouddy=appCode(appName)==='clouddy',usesMac=appUsesMac(appName);row.querySelectorAll('.mac-key-field').forEach(label=>label.hidden=!usesMac);row.querySelectorAll('.clouddy-email-field').forEach(label=>label.hidden=!isClouddy)}
function renderDevices(devices=[newDevice()]){const list=$('devicesList'),rows=devices.length?devices:[newDevice()];list.innerHTML=rows.map((d,i)=>`<div class="device-entry"><label>Dispositivo<input data-device="device" value="${escapeHTML(d.device||`TV ${i+1}`)}" placeholder="TV 1"></label><label>Aplicativo<input data-device="appName" list="apps" value="${escapeHTML(d.appName||'')}" placeholder="XCloud TV"></label><label class="clouddy-email-field">E-mail do Clouddy<input data-device="email" type="email" value="${escapeHTML(d.email||'')}" placeholder="E-mail da conta Clouddy"></label><label>Usuário<input data-device="username" value="${escapeHTML(d.username||'')}" placeholder="Usuário do cliente"></label><label>Senha<input data-device="password" value="${escapeHTML(d.password||'')}" placeholder="Senha do cliente"></label><label class="mac-key-field">MAC<input data-device="mac" maxlength="17" value="${escapeHTML(formatMac(d.mac||''))}" placeholder="AA:BB:CC:11:22:33"></label><label class="mac-key-field">Key<input data-device="key" value="${escapeHTML(d.key||'')}" placeholder="123456789"></label><label>Valor pago no aplicativo (R$)<input data-device="appPrice" type="number" min="0" step="0.01" value="${d.appPrice==null?'':escapeHTML(d.appPrice)}" placeholder="Deixe vazio se for grátis"></label><label>Telas<select data-device="screens">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option value="${n}" ${Number(d.screens||1)===n?'selected':''}>${n}</option>`).join('')}</select></label><button type="button" class="remove-device">×</button></div>`).join('');list.querySelectorAll('.device-entry').forEach(row=>{const app=row.querySelector('[data-device="appName"]'),mac=row.querySelector('[data-device="mac"]');app.addEventListener('input',()=>updateDeviceAccess(row));app.addEventListener('change',()=>updateDeviceAccess(row));mac.addEventListener('input',()=>{mac.value=formatMac(mac.value)});updateDeviceAccess(row)});list.querySelectorAll('.remove-device').forEach(b=>b.onclick=()=>{if(list.children.length>1)b.parentElement.remove()})}
function getDevices(){return [...document.querySelectorAll('.device-entry')].map(r=>{const v=k=>r.querySelector(`[data-device="${k}"]`)?.value.trim()||'',appName=v('appName'),usesMac=appUsesMac(appName);return{device:v('device'),appName,email:appCode(appName)==='clouddy'?v('email'):'',username:v('username'),password:v('password'),mac:usesMac?v('mac'):'',key:usesMac?v('key'):'',appPrice:v('appPrice'),screens:Number(v('screens'))||1}}).filter(d=>d.appName||d.email||d.username||d.mac||d.key)}
function renderResellerDatalist(){$('resellerNames').innerHTML=resellers.map(r=>`<option value="${escapeHTML(r.name)}"></option>`).join('')}
function resellerMessage(name,group){const due=group.filter(c=>!c.cancelled&&!c.lifetime&&diffDays(c.dueDate)<=5);let t=`Olá, ${name}! Segue a cobrança dos seus clientes na JS Tech.\n\n`;if(!due.length)t+='Nenhum cliente vence nos próximos 5 dias.\n';due.forEach(c=>{t+=`Cliente: ${c.name}\nAplicativos:\n${(c.devices||[]).map(d=>`• ${d.device}: ${d.appName} · ${d.screens} tela${d.screens>1?'s':''}${d.appPrice!==''&&d.appPrice!=null?` · ${money(d.appPrice)}`:''}`).join('\n')}\nCadastro: ${dateBR(c.startDate)}\nVencimento: ${dateBR(c.dueDate)}\nValor do plano: ${money(c.value)}\nSituação: ${statusOf(c).label}\n\n`});return t+'JS Tech — conectado com você.'}
function renderResellers(){const q=$('resellerSearch').value.toLowerCase().trim(),groups={};resellers.forEach(r=>groups[r.name]=[]);clients.forEach(c=>{const n=c.resellerName||DIRECT_RESELLER;(groups[n]||(groups[n]=[])).push(c)});const valid=clients.filter(c=>!c.cancelled),revenue=valid.reduce((t,c)=>t+c.value,0),cost=valid.reduce((t,c)=>t+c.cost,0);$('generalRevenue').textContent=money(revenue);$('generalCost').textContent=money(cost);$('generalProfit').textContent=money(revenue-cost);$('generalResellers').textContent=resellers.length;const entries=Object.entries(groups).filter(([n,g])=>!q||n.toLowerCase().includes(q)||g.some(c=>c.name.toLowerCase().includes(q)));$('resellersEmpty').hidden=!!entries.length;$('resellersTree').innerHTML=entries.map(([n,g])=>{const rr=resellers.find(x=>x.name===n),a=g.filter(c=>!c.cancelled),r=a.reduce((t,c)=>t+c.value,0),ct=a.reduce((t,c)=>t+c.cost,0),phone=rr?.phone||g.find(c=>c.resellerPhone)?.resellerPhone||'',action=n===DIRECT_RESELLER?'':`${phone?`<a class="action-btn" target="_blank" href="https://wa.me/${whatsappNumber(phone)}?text=${encodeURIComponent(resellerMessage(n,g))}">Cobrar no WhatsApp</a>`:'<span class="badge gray">Sem WhatsApp</span>'}<button class="action-btn" onclick="openClientForReseller('${rr?.id||''}')">+ Cliente do revendedor</button>`;return `<section class="reseller-card"><div class="reseller-head"><div><h3>${escapeHTML(n)}</h3><p>${g.length} cliente(s) ${phone?'· '+escapeHTML(phone):''}</p></div><div class="reseller-totals"><div><span>Faturamento</span><strong>${money(r)}</strong></div><div><span>Apps pagos</span><strong>${money(ct)}</strong></div><div><span>Lucro</span><strong class="positive">${money(r-ct)}</strong></div>${action}</div></div>${g.length?g.map(c=>`<div class="reseller-client"><div><strong>${escapeHTML(c.name)}</strong><small>${escapeHTML(c.phone)}</small></div><div>${(c.devices||[]).map(d=>`${escapeHTML(d.device)}: ${escapeHTML(d.appName)} · ${d.screens} tela(s)${d.appPrice!==''&&d.appPrice!=null?` · ${money(d.appPrice)}`:''}`).join('<br>')}<small>${dateBR(c.startDate)} → ${c.lifetime?'Vitalício':dateBR(c.dueDate)}</small></div><div>Venda<br><strong>${money(c.value)}</strong></div><div>Apps pagos<br><strong>${money(c.cost)}</strong></div><div class="positive">Lucro<br><strong>${money(c.value-c.cost)}</strong></div><span class="badge ${statusOf(c).color}">${statusOf(c).label}</span></div>`).join(''):'<div class="reseller-empty-row">Nenhum cliente. Clique em “Cliente do revendedor”.</div>'}</section>`}).join('')}
async function loadAndroidApps(){try{androidApps=await api('/rest/v1/android_apps?select=id,name,price&active=eq.true&order=name.asc')}catch{androidApps=[]}$('androidAppsGrid').innerHTML=androidApps.map(a=>`<article class="android-app-card"><strong>${escapeHTML(a.name)}</strong><span>Aplicativo Android</span><label>Valor padrão (opcional)<input class="android-price" data-app-id="${a.id}" type="number" min="0" step="0.01" value="${a.price==null?'':a.price}" placeholder="Em branco"><button class="ghost small" onclick="saveAndroidPrice('${a.id}')">Salvar valor</button></label></article>`).join('');$('apps').innerHTML=androidApps.map(a=>`<option>${escapeHTML(a.name)}</option>`).join('')}
async function saveAndroidPrice(id){const input=document.querySelector(`[data-app-id="${id}"]`),price=input.value===''?null:Number(input.value);try{await api(`/rest/v1/android_apps?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({price})});showToast('Valor do aplicativo salvo.')}catch(e){alert(e.message)}}
async function saveAndroidApp(){const name=$('newAndroidAppName').value.trim(),price=$('newAndroidAppPrice').value===''?null:Number($('newAndroidAppPrice').value);if(!name){alert('Digite o nome do aplicativo.');return}try{await api('/rest/v1/android_apps?on_conflict=owner_id,name',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({name,price,active:true})});$('newAndroidAppName').value='';$('newAndroidAppPrice').value='';await loadAndroidApps();showToast('Aplicativo cadastrado.')}catch(e){alert(e.message)}}
function setPanelView(view){const apps=view==='apps',resellers=view==='resellers',finance=view==='finance',special=apps||resellers||finance;document.querySelector('.topbar').hidden=special;document.querySelector('.analytics').hidden=!finance;document.querySelector('.monthly-report').hidden=!finance;document.querySelector('.summary-grid').hidden=special;document.querySelector('.panel:not(#resellersSection):not(#androidAppsSection):not(.monthly-report)').hidden=special;$('resellersSection').hidden=!resellers;$('androidAppsSection').hidden=!apps;if(resellers)renderResellers();if(apps)loadAndroidApps();if(finance){renderAnalytics();renderMonthlyReport()}}
function clientRow(c){const s=statusOf(c),days=c.lifetime?999:diffDays(c.dueDate),hint=c.lifetime?'Sem vencimento':days<0?`${Math.abs(days)} dia${Math.abs(days)>1?'s':''} atrasado`:days===0?'É hoje':days===1?'Amanhã':`Faltam ${days} dias`;return `<tr><td class="client-name"><strong>${escapeHTML(c.name)}</strong><span>${escapeHTML(c.phone)}</span></td><td>${escapeHTML((c.devices||[]).map(d=>d.appName).join(', '))}</td><td>${c.lifetime?'Vitalício':planLabel(c.plan)} · ${c.screens} tela(s)</td><td class="date-cell"><strong>${c.lifetime?'Vitalício':dateBR(c.dueDate)}</strong><span>${c.cancelled?'Sem renovação':hint}</span></td><td><strong>${money(c.value)}</strong></td><td><span class="badge ${s.color}">${s.label}</span></td><td><div class="actions">${c.lifetime?'':`<button class="action-btn renew" onclick="renewClient('${c.id}')">Renovar</button>`}<button class="action-btn" onclick="sendCharge('${c.id}')">WhatsApp</button><button class="action-btn" onclick="showClientData('${c.id}')">Ver dados</button><details class="more"><summary class="action-btn">•••</summary><div class="more-menu"><button onclick="editClient('${c.id}')">Editar</button><button onclick="showHistory('${c.id}')">Histórico</button><button onclick="toggleCancel('${c.id}')">${c.cancelled?'Reativar':'Cancelar'}</button><button class="danger" onclick="deleteClient('${c.id}')">Excluir</button></div></details></div></td></tr>`}
function configureClientPhoneRequirement(isResellerClient){const phone=$('phone'),hint=$('clientPhoneHint');phone.required=!isResellerClient;phone.placeholder=isResellerClient?'Opcional — a cobrança vai para o revendedor':'(27) 99999-9999';hint.textContent=isResellerClient?'Opcional: será usado o WhatsApp do revendedor.':''}
function openForm(c=null){$('clientForm').reset();delete $('clientForm').dataset.detectedDue;$('clientId').value=c?.id||'';$('formTitle').textContent=c?'Editar cliente':'Novo cliente';$('startDate').value=c?.startDate||isoToday();$('plan').value=c?.plan||'30d';$('screens').value=String(c?.screens||1);$('lifetime').checked=!!c?.lifetime;renderDevices(c?.devices||[newDevice()]);if(c){$('name').value=c.name;$('phone').value=c.phone||'';$('value').value=c.value;$('resellerName').value=c.resellerName||'';$('resellerPhone').value=c.resellerPhone||'';$('payment').value=c.payment;$('notes').value=c.notes||''}configureClientPhoneRequirement(!!c?.resellerId||!!c?.resellerName);updatePreview();$('clientDialog').showModal()}
function openClientForReseller(id){const r=resellers.find(x=>x.id===id);openForm();if(r){$('resellerName').value=r.name;$('resellerPhone').value=r.phone||'';configureClientPhoneRequirement(true)}}
function updatePreview(){const lifetime=$('lifetime').checked;$('plan').disabled=lifetime;$('datePreview').textContent=lifetime?'Vitalício — sem vencimento':$('startDate').value?dateBR(calculateDue($('startDate').value,$('plan').value)):'—'}
function deviceDataText(d,i){const access=appUsesMac(d.appName)?`\nMAC: ${d.mac||'—'}\nKey: ${d.key||'—'}`:'',email=appCode(d.appName)==='clouddy'?`\nE-mail: ${d.email||'—'}`:'';return `${d.device||`Aparelho ${i+1}`}\nAplicativo Android: ${d.appName||'—'}${email}\nUsuário: ${d.username||'—'}\nSenha: ${d.password||'—'}${access}\nTelas: ${d.screens||1}\nValor do aplicativo: ${d.appPrice!==''&&d.appPrice!=null?money(d.appPrice):'Grátis / não informado'}`}
function showClientData(id){const c=clients.find(x=>x.id===id);if(!c)return;clientDataId=id;const devices=c.devices||[];clientDataText=`Cliente: ${c.name}\nWhatsApp: ${c.phone}\nPlano: ${c.lifetime?'Vitalício':planLabel(c.plan)}\nCadastro: ${dateBR(c.startDate)}\nVencimento: ${c.lifetime?'Sem vencimento':dateBR(c.dueDate)}\nValor: ${money(c.value)}\nRevendedor: ${c.resellerName||'Cliente direto'}\n\n`+devices.map(deviceDataText).join('\n\n');$('clientDataTitle').textContent=c.name;$('clientDataContent').innerHTML=`<div class="data-summary"><div><span>WhatsApp</span><strong>${escapeHTML(c.phone)}</strong></div><div><span>Plano</span><strong>${c.lifetime?'Vitalício':escapeHTML(planLabel(c.plan))}</strong></div><div><span>Vencimento</span><strong>${c.lifetime?'Sem vencimento':dateBR(c.dueDate)}</strong></div><div><span>Responsável</span><strong>${escapeHTML(c.resellerName||'Cliente direto')}</strong></div></div>`+devices.map((d,i)=>{const macKey=appUsesMac(d.appName)?`<div><span>MAC</span><strong>${escapeHTML(d.mac||'—')}</strong></div><div><span>Key</span><strong>${escapeHTML(d.key||'—')}</strong></div>`:'';return `<section class="data-device"><div class="data-device-head"><div><span>${escapeHTML(d.device||`Aparelho ${i+1}`)}</span><h3>${escapeHTML(d.appName||'Aplicativo não informado')}</h3></div><b>Aplicativo Android</b></div><div class="data-fields"><div><span>Usuário</span><strong>${escapeHTML(d.username||'—')}</strong></div><div><span>Senha</span><strong>${escapeHTML(d.password||'—')}</strong></div>${macKey}<div><span>Telas</span><strong>${d.screens||1}</strong></div><div><span>Valor do aplicativo</span><strong>${d.appPrice!==''&&d.appPrice!=null?money(d.appPrice):'Grátis / não informado'}</strong></div></div></section>`}).join('');$('moveClientReseller').innerHTML=`<option value="">Cliente direto</option>`+resellers.map(r=>`<option value="${r.id}" ${c.resellerId===r.id?'selected':''}>${escapeHTML(r.name)}</option>`).join('');$('clientDataDialog').showModal()}
async function moveClientToReseller(){const c=clients.find(x=>x.id===clientDataId);if(!c)return;const id=$('moveClientReseller').value,r=resellers.find(x=>x.id===id);try{setBusy(true);c.resellerId=id||null;c.resellerName=r?.name||'';c.resellerPhone=r?.phone||'';await api(`/rest/v1/clients?id=eq.${c.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({reseller_id:c.resellerId,notes:fromClient(c).notes})});await addHistory(c,'update',c.dueDate,c.dueDate,`Cliente movido para ${c.resellerName||'Cliente direto'}`);$('clientDataDialog').close();render();showToast(`Cliente movido para ${c.resellerName||'Cliente direto'}.`)}catch(e){alert(e.message)}finally{setBusy(false)}}
function editClient(id){openForm(clients.find(c=>c.id===id))}
async function addHistory(c,type,oldDue,newDue,description,amount=0){const rows=await api('/rest/v1/renewals',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({client_id:c.id,event_type:type,plan:c.plan,amount,previous_due_date:oldDue,new_due_date:newDue,description})});if(rows[0])renewals.unshift(rows[0]);return rows[0]}
async function renewClient(id){const c=clients.find(c=>c.id===id);if(!c)return;const base=diffDays(c.dueDate)>=0?c.dueDate:isoToday(),oldDue=c.dueDate,newDue=calculateDue(base,c.plan);try{setBusy(true);await api(`/rest/v1/clients?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({due_date:newDue,cancelled:false})});await addHistory(c,'renewal',oldDue,newDue,`Renovado por ${planLabel(c.plan)}`,c.value);c.dueDate=newDue;c.cancelled=false;c.lastRenewedAt=isoToday();render();showToast(`Renovação de ${c.name} registrada.`);showMessage(c,'renewal')}catch(e){alert(e.message)}finally{setBusy(false)}}
async function toggleCancel(id){const c=clients.find(c=>c.id===id);if(!c)return;try{setBusy(true);const cancelled=!c.cancelled;await api(`/rest/v1/clients?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({cancelled})});await addHistory(c,cancelled?'cancel':'reactivate',c.dueDate,c.dueDate,cancelled?'Cliente cancelado':'Cliente reativado');c.cancelled=cancelled;render()}catch(e){alert(e.message)}finally{setBusy(false)}}
async function deleteClient(id){const c=clients.find(c=>c.id===id);if(!c||!confirm(`Excluir definitivamente o cadastro de ${c.name}?`))return;try{setBusy(true);await api(`/rest/v1/clients?id=eq.${id}`,{method:'DELETE'});clients=clients.filter(x=>x.id!==id);renewals=renewals.filter(x=>x.client_id!==id);render();showToast('Cliente excluído.')}catch(e){alert(e.message)}finally{setBusy(false)}}
async function showHistory(id){const c=clients.find(c=>c.id===id);if(!c)return;try{const rows=await api(`/rest/v1/renewals?client_id=eq.${id}&select=*&order=created_at.desc`);$('historyTitle').textContent=c.name;$('historyContent').innerHTML=rows.map(h=>`<div class="history-item"><strong>${escapeHTML(h.description)}</strong><span>${dateBR(h.created_at.slice(0,10))}${Number(h.amount)?` · ${money(h.amount)}`:''}</span></div>`).join('')||'<p>Nenhum registro encontrado.</p>';$('historyDialog').showModal()}catch(e){alert(e.message)}}
function activationMessage(c,renewal=false){const access=(c.devices||[]).map((d,i)=>{const email=appCode(d.appName)==='clouddy'?`\nE-mail: ${d.email||'—'}`:'',macKey=appUsesMac(d.appName)?`\nMAC: ${d.mac||'—'}\nKey: ${d.key||'—'}`:'';return `\n${d.device||`Aparelho ${i+1}`}\nAplicativo: ${d.appName||'—'}${email}\nUsuário: ${d.username||'—'}\nSenha: ${d.password||'—'}${macKey}`}).join('\n');return `Olá, ${c.name}! Seu pacote de ${c.lifetime?'Vitalício':planLabel(c.plan)} foi ${renewal?'renovado':'ativado'} com sucesso.\n${access}\n\nData da ${renewal?'renovação':'contratação'}: ${dateBR(renewal?(c.lastRenewedAt||isoToday()):c.startDate)}\nVencimento: ${c.lifetime?'Sem vencimento':dateBR(c.dueDate)}\n\nAgradecemos pela preferência!\nJS Tech — conectado com você.`}
const PIX_KEY='f721b8e2-1ad2-469c-b45d-653e58880ba2';
function chargeMessage(c){const reseller=c.resellerName?`Olá, ${c.resellerName}! Tudo bem?\n\nO cliente ${c.name}, da sua revenda,`:`Olá, ${c.name}! Tudo bem?\n\nSeu plano`;return `${reseller} de ${c.lifetime?'Vitalício':planLabel(c.plan)} ${!c.lifetime?(diffDays(c.dueDate)<0?`venceu em ${dateBR(c.dueDate)}`:`vence em ${dateBR(c.dueDate)}`):'está ativo'}. O valor para renovação é ${money(c.value)}.\n\nPagamento via Pix\nChave Pix: ${PIX_KEY}\nTitular: Julio Viana de Oliveira\n\nApós o pagamento, envie o comprovante para confirmar a renovação.\nJS Tech — conectado com você.`}
function showMessage(c,type){messageClientId=c.id;$('messageTitle').textContent=type==='charge'?'Aviso de vencimento':type==='renewal'?'Renovação realizada':'Ativação realizada';$('messageText').value=type==='charge'?chargeMessage(c):activationMessage(c,type==='renewal');$('messageDialog').showModal()}
function sendCharge(id){const c=clients.find(c=>c.id===id);if(c)showMessage(c,'charge')}
function whatsappNumber(phone){let n=phone.replace(/\D/g,'');if(n.length===10||n.length===11)n='55'+n;return n}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').style.color='';$('loginError').textContent='';const username=$('loginUser').value.trim().toLowerCase(),password=$('loginPassword').value;if(username!==ADMIN_USER){$('loginError').textContent='Usuário ou senha incorretos.';return}try{setBusy(true);let data;try{data=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:ADMIN_EMAIL,password})})}catch{const redirect=encodeURIComponent(location.origin);data=await api(`/auth/v1/signup?redirect_to=${redirect}`,{method:'POST',body:JSON.stringify({email:ADMIN_EMAIL,password})});if(!data.access_token){$('loginError').style.color='#43d99c';$('loginError').textContent='Primeiro acesso criado. Confirme o e-mail enviado para juliosirlene43@gmail.com e depois clique em Entrar.';return}}data.expires_at=Math.floor(Date.now()/1000)+data.expires_in;storeSession(data);await enterApp()}catch(e){$('loginError').style.color='';$('loginError').textContent='Não foi possível entrar. Confira o usuário e a senha.'}finally{setBusy(false)}});
$('logoutBtn').addEventListener('click',async()=>{try{await api('/auth/v1/logout',{method:'POST'})}catch{}clearSession();clients=[];renewals=[];showLogin()});
$('clientForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('clientId').value,existing=clients.find(c=>c.id===id),oldDue=existing?.dueDate||null,lifetime=$('lifetime').checked,devices=getDevices(),appCost=devices.reduce((total,d)=>total+(d.appPrice===''?0:Number(d.appPrice)||0),0),data={name:$('name').value.trim(),phone:$('phone').value.trim(),devices,startDate:$('startDate').value,plan:$('plan').value,value:Number($('value').value),cost:appCost,resellerName:$('resellerName').value.trim(),resellerPhone:$('resellerPhone').value.trim(),payment:$('payment').value,notes:$('notes').value.trim(),screens:Number($('screens').value)||1,lifetime,cancelled:existing?.cancelled||false};data.dueDate=lifetime?(existing?.dueDate||calculateDue(data.startDate,data.plan)):($('clientForm').dataset.detectedDue||calculateDue(data.startDate,data.plan));try{setBusy(true);data.resellerId=await ensureReseller(data.resellerName,data.resellerPhone);if(existing){await api(`/rest/v1/clients?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(fromClient(data))});await syncClientApps(id,data);Object.assign(existing,data);await addHistory(existing,'update',oldDue,data.dueDate,`Cadastro atualizado${lifetime?' · Vitalício':''}`);$('clientDialog').close();render();showToast('Cadastro atualizado.')}else{const rows=await api('/rest/v1/clients',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(fromClient(data))});const c=toClient(rows[0]);await syncClientApps(c.id,data);Object.assign(c,data);clients.push(c);await addHistory(c,'sale',null,c.dueDate,`Venda cadastrada: ${lifetime?'Vitalício':planLabel(c.plan)}`,c.value);$('clientDialog').close();render();showMessage(c,'activation')}}catch(e){alert(e.message)}finally{setBusy(false)}});
document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>$('clientDialog').close()));document.querySelectorAll('.close-message').forEach(b=>b.addEventListener('click',()=>$('messageDialog').close()));document.querySelectorAll('.close-history').forEach(b=>b.addEventListener('click',()=>$('historyDialog').close()));
document.querySelectorAll('.close-client-data').forEach(b=>b.addEventListener('click',()=>$('clientDataDialog').close()));$('copyClientDataBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(clientDataText);showToast('Dados do cliente copiados.')});
$('moveClientBtn').addEventListener('click',moveClientToReseller);
document.querySelectorAll('.close-reseller').forEach(b=>b.addEventListener('click',()=>$('resellerDialog').close()));
$('newResellerBtn').addEventListener('click',()=>{$('resellerForm').reset();$('resellerDialog').showModal()});
$('resellerForm').addEventListener('submit',async e=>{e.preventDefault();try{setBusy(true);await api('/rest/v1/resellers?on_conflict=owner_id,name',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({name:$('newResellerName').value.trim(),phone:$('newResellerPhone').value.trim(),notes:$('newResellerNotes').value.trim(),active:true})});$('resellerDialog').close();await loadData();setPanelView('resellers');showToast('Revendedor cadastrado. Agora adicione os clientes dele.')}catch(e){alert(e.message)}finally{setBusy(false)}});
$('newClientBtn').addEventListener('click',()=>openForm());$('addDeviceBtn').addEventListener('click',()=>{const d=getDevices();d.push(newDevice(`TV ${d.length+1}`));renderDevices(d)});$('emptyAddBtn').addEventListener('click',()=>openForm());$('startDate').addEventListener('change',updatePreview);$('plan').addEventListener('change',updatePreview);$('lifetime').addEventListener('change',updatePreview);$('searchInput').addEventListener('input',render);$('sortSelect').addEventListener('change',render);$('resellerSearch').addEventListener('input',renderResellers);$('saveAndroidAppBtn').addEventListener('click',saveAndroidApp);
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.view){setPanelView(b.dataset.view);return}setPanelView('clients');activeFilter=b.dataset.filter;render()}));
document.querySelectorAll('.period-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.period-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');dashboardPeriod=b.dataset.period;$('customDates').hidden=dashboardPeriod!=='custom';renderAnalytics()}));
$('applyPeriod').addEventListener('click',renderAnalytics);
$('copyMessageBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText($('messageText').value);showToast('Mensagem copiada.')});$('openWhatsappBtn').addEventListener('click',()=>{const c=clients.find(c=>c.id===messageClientId);if(c){const destination=c.resellerId||c.resellerName?c.resellerPhone:c.phone;if(!destination){alert('Cadastre o WhatsApp do revendedor responsável.');return}window.open(`https://wa.me/${whatsappNumber(destination)}?text=${encodeURIComponent($('messageText').value)}`,'_blank','noopener')}});
$('resellerName').addEventListener('input',()=>configureClientPhoneRequirement(!!$('resellerName').value.trim()));
$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),clients},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-js-tech-${isoToday()}.json`;a.click();URL.revokeObjectURL(a.href);showToast('Backup baixado.')});
$('importInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.clients))throw new Error();if(confirm(`Importar ${data.clients.length} cliente(s) para o banco?`)){setBusy(true);for(const item of data.clients){const rows=await api('/rest/v1/clients',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(fromClient(item))});if(rows[0])await addHistory(toClient(rows[0]),'sale',null,rows[0].due_date,'Venda importada',Number(rows[0].amount||0))}await loadData();showToast('Backup importado.')}}catch{alert('Este arquivo de backup não é válido ou não pôde ser importado.')}finally{setBusy(false);e.target.value=''}});
$('todayText').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());
$('periodStart').value=formatISO(new Date(today().getFullYear(),today().getMonth(),1));$('periodEnd').value=isoToday();
function renderMonthlyReport(){const months=[];const now=today();for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;const sales=renewals.filter(r=>['sale','renewal'].includes(r.event_type)&&String(r.created_at||'').slice(0,7)===key),fallback=clients.filter(c=>String(c.startDate||'').slice(0,7)===key),rows=sales.length?sales:fallback.map(c=>({amount:c.value})),total=rows.reduce((sum,r)=>sum+Number(r.amount||0),0);months.push({label:new Intl.DateTimeFormat('pt-BR',{month:'short',year:'numeric'}).format(d),count:rows.length,total})}const max=Math.max(...months.map(m=>m.total),1);$('monthlyReport').innerHTML=months.map(m=>`<article class="month-card"><div><span>${m.label}</span><strong>${money(m.total)}</strong></div><small>${m.count} venda${m.count===1?'':'s'}/renovaç${m.count===1?'ão':'ões'}</small><div class="month-bar"><i style="width:${Math.round(m.total/max*100)}%"></i></div></article>`).join('')}
function parseM3UUrl(value=''){try{const u=new URL(value);const q=u.searchParams;const username=q.get('username')||q.get('user')||'';const password=q.get('password')||q.get('pass')||'';const exp=q.get('exp_date')||q.get('expires')||'';return{username,password,due:exp&&/^\d+$/.test(exp)?new Date(Number(exp)*1000):null}}catch{return{username:'',password:'',due:null}}}
function activationFromDue(dueDate,plan,reportedDate=''){if(!dueDate)return reportedDate;const d=parseDate(dueDate);if(plan==='1y')d.setFullYear(d.getFullYear()-1);else if(plan==='6m')d.setMonth(d.getMonth()-6);else if(plan==='3m')d.setMonth(d.getMonth()-3);else if(plan==='30d')d.setDate(d.getDate()-30);else return reportedDate;return formatISO(d)}
async function checkM3UDetails(value,row,status){const parsed=parseM3UUrl(value),user=row.querySelector('[data-device="username"]'),pass=row.querySelector('[data-device="password"]');if(parsed.username)user.value=parsed.username;if(parsed.password)pass.value=parsed.password;if(!parsed.username||!parsed.password){status.textContent='Cole uma URL completa com usuário e senha.';return}status.textContent='Verificando todos os dados disponíveis…';try{const info=await api('/functions/v1/check-m3u',{method:'POST',body:JSON.stringify({url:value})});if(info.username)user.value=info.username;if(info.password)pass.value=info.password;if(info.customerName&&!$('name').value.trim())$('name').value=info.customerName;if(info.customerPhone&&!$('phone').value.trim())$('phone').value=info.customerPhone;const screen=row.querySelector('[data-device="screens"]');if(screen&&info.maxConnections){screen.value=String(Math.min(10,Number(info.maxConnections)||1));const total=[...document.querySelectorAll('.device-entry [data-device="screens"]')].reduce((n,s)=>n+(Number(s.value)||1),0);$('screens').value=String(Math.min(10,total))}let detectedPlan=$('plan').value;if(info.createdDate&&info.dueDate){const days=Math.round((parseDate(info.dueDate)-parseDate(info.createdDate))/86400000);detectedPlan=days<=45?'30d':days<=120?'3m':days<=220?'6m':'1y';$('plan').value=detectedPlan}const activationDate=activationFromDue(info.dueDate,detectedPlan,info.createdDate);if(activationDate)$('startDate').value=activationDate;if(info.dueDate&&!$('lifetime').checked){$('clientForm').dataset.detectedDue=info.dueDate;$('datePreview').textContent=dateBR(info.dueDate)}updatePreview();if(info.dueDate&&!$('lifetime').checked)$('datePreview').textContent=dateBR(info.dueDate);status.textContent=`✓ ${info.customerName?'Cliente: '+info.customerName+' · ':''}${info.customerPhone?'Telefone: '+info.customerPhone+' · ':''}${activationDate?'Criado em '+dateBR(activationDate)+' · ':''}${info.dueDate?'Vence em '+dateBR(info.dueDate):'Vencimento não informado'} · ${info.maxConnections||1} tela(s)`}catch(e){status.textContent=e.message||'Não foi possível consultar esta URL.'}}
function addM3UFields(devices=[]){document.querySelectorAll('.device-entry').forEach((row,i)=>{if(row.querySelector('[data-device="m3uUrl"]'))return;const app=row.querySelector('[data-device="appName"]')?.closest('label'),label=document.createElement('label');label.innerHTML=`URL M3U<input data-device="m3uUrl" value="${escapeHTML(devices[i]?.m3uUrl||'')}" placeholder="Cole a URL M3U completa"><small class="m3u-status"></small>`;app?.after(label);const url=label.querySelector('input'),status=label.querySelector('.m3u-status');let timer;url.addEventListener('input',()=>{clearTimeout(timer);const p=parseM3UUrl(url.value),user=row.querySelector('[data-device="username"]'),pass=row.querySelector('[data-device="password"]');if(p.username)user.value=p.username;if(p.password)pass.value=p.password;status.textContent=url.value?'Aguardando consulta…':'';if(url.value)timer=setTimeout(()=>checkM3UDetails(url.value,row,status),700)});if(url.value)timer=setTimeout(()=>checkM3UDetails(url.value,row,status),300)})}
const originalRenderDevices=renderDevices;renderDevices=devices=>{originalRenderDevices(devices);addM3UFields(devices)};
const originalGetDevices=getDevices;getDevices=()=>{const rows=originalGetDevices();return rows.map((d,i)=>{const row=document.querySelectorAll('.device-entry')[i],m=row?.querySelector('[data-device="m3uUrl"]')?.value.trim()||'';return{...d,m3uUrl:m}})};
const originalSyncClientApps=syncClientApps;syncClientApps=async(id,d)=>{await originalSyncClientApps(id,d);for(const x of d.devices||[]){if(x.m3uUrl)await api('/rest/v1/client_apps?client_id=eq.'+encodeURIComponent(id)+'&device_name=eq.'+encodeURIComponent(x.device||'Dispositivo'),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({m3u_url:x.m3uUrl})})}};
const originalLoadData=loadData;loadData=async()=>{await originalLoadData();const rows=await api('/rest/v1/client_apps?select=client_id,device_name,m3u_url&active=eq.true');rows.forEach(a=>{const c=clients.find(x=>x.id===a.client_id),d=c?.devices?.find(x=>x.device===a.device_name);if(d)d.m3uUrl=a.m3u_url||''});render()};
const originalRender=render;render=()=>{originalRender();renderMonthlyReport();addM3UFields()};
const originalShowClientData=showClientData;showClientData=id=>{originalShowClientData(id);const c=clients.find(x=>x.id===id);document.querySelectorAll('#clientDataContent .data-device').forEach((section,i)=>{const d=c?.devices?.[i];if(appCode(d?.appName)==='clouddy'){const fields=section.querySelector('.data-fields'),box=document.createElement('div');box.innerHTML=`<span>E-mail do Clouddy</span><strong>${escapeHTML(d.email||'—')}</strong>`;fields?.prepend(box)}})};
init();

// JSTECH AUTO-INTEGRATION START
/* Ponte de compatibilidade: as melhorias usam a mesma sessão e a mesma API do app.js. */
(function(){
  'use strict';
  function sync(){
    try{
      if(typeof session!=='undefined') window.session=session;
      if(typeof clients!=='undefined') window.clients=clients;
      if(typeof renewals!=='undefined') window.renewals=renewals;
    }catch(e){}
  }
  sync();
  setInterval(sync,1000);

  const originalFetch=window.fetch.bind(window);
  window.fetch=function(input,init){
    try{
      const url=typeof input==='string'?input:(input&&input.url)||'';
      if(url.includes('yifgptxujimzsjoeghte.supabase.co')){
        const h=new Headers((init&&init.headers)||{});
        const token=typeof session!=='undefined'&&session?.access_token?session.access_token:null;
        if(token){
          h.set('Authorization','Bearer '+token);
          h.set('apikey',typeof SUPABASE_KEY!=='undefined'?SUPABASE_KEY:'');
        }
        init={...(init||{}),headers:h};
      }
    }catch(e){}
    return originalFetch(input,init);
  };
})();


/* JSTECH ENHANCEMENTS START
 * Camada complementar do painel JS Tech. Carregada pelo workflow no app.js.
 */
(function(){
  'use strict';
  const ACTIVATION_URL='https://ativacaodeaplicativos.com/';
  const OWNER_EMAIL='juliosirlene43@gmail.com';
  const fmtMoney=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  const todayISO=()=>new Date().toISOString().slice(0,10);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const toast=msg=>typeof window.showToast==='function'?window.showToast(msg):alert(msg);
  const uid=()=>window.session?.user?.id||window.currentUser?.id||null;
  async function rest(path,opts={}){
    const r=await fetch((window.SUPABASE_URL||'https://yifgptxujimzsjoeghte.supabase.co')+path,{...opts,headers:{apikey:window.SUPABASE_KEY||'',Authorization:'Bearer '+(window.session?.access_token||window.SUPABASE_KEY||''),'Content-Type':'application/json',...(opts.headers||{})}});
    if(!r.ok) throw new Error(await r.text());
    return r.status===204?null:r.json();
  }
  function addStyle(){if(document.getElementById('jstech-enh-style'))return;const s=document.createElement('style');s.id='jstech-enh-style';s.textContent=`
  .jstech-enh{margin:18px 0;padding:18px;border:1px solid var(--border,#ddd);border-radius:16px;background:var(--card,#fff);box-shadow:0 8px 28px #0000000d}.jstech-enh h3{margin:0 0 12px}.je-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.je-stat{padding:13px;border-radius:12px;background:var(--surface,#f5f6f8)}.je-stat b{display:block;font-size:20px}.je-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.je-btn{border:0;border-radius:10px;padding:9px 12px;cursor:pointer}.je-primary{background:#2563eb;color:#fff}.je-success{background:#16a34a;color:#fff}.je-warn{background:#f59e0b;color:#111}.je-danger{background:#dc2626;color:#fff}.je-input{width:100%;box-sizing:border-box;padding:9px;border:1px solid #ccc;border-radius:9px}.je-table{width:100%;border-collapse:collapse;margin-top:12px}.je-table th,.je-table td{padding:8px;border-bottom:1px solid #eee;text-align:left;font-size:13px}.je-pill{display:inline-block;padding:4px 8px;border-radius:999px;font-size:12px}.je-paid{background:#dcfce7;color:#166534}.je-pending{background:#fef3c7;color:#92400e}.je-overdue{background:#fee2e2;color:#991b1b}.je-modal{position:fixed;inset:0;background:#0008;z-index:99999;display:none;align-items:center;justify-content:center;padding:15px}.je-box{background:#fff;color:#111;width:min(760px,96vw);max-height:90vh;overflow:auto;border-radius:16px;padding:18px}.je-close{float:right;border:0;background:none;font-size:24px;cursor:pointer}.je-activation iframe{width:100%;height:520px;border:1px solid #ddd;border-radius:12px}.je-muted{opacity:.7;font-size:12px}`;document.head.appendChild(s)}
  function modal(id,title,body){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.className='je-modal';document.body.appendChild(m)}m.innerHTML=`<div class="je-box"><button class="je-close" data-je-close="${id}">×</button><h3>${title}</h3>${body}</div>`;m.style.display='flex';return m}
  document.addEventListener('click',async e=>{
    const close=e.target.closest('[data-je-close]');if(close){document.getElementById(close.dataset.jeClose).style.display='none';return}
    const b=e.target.closest('[data-je-action]');if(!b)return;const a=b.dataset.jeAction;
    try{if(a==='payment')await paymentModal(b.dataset.id);if(a==='charge')await chargeClient(b.dataset.id,b.dataset.type||'manual');if(a==='history')await historyClient(b.dataset.id);if(a==='pix')await pixModal();if(a==='activation')activationModal();if(a==='backup')await backupNow();if(a==='report')await reportModal();if(a==='advanced')advancedSearch();if(a==='password'){const x=document.getElementById(b.dataset.target);if(x){x.type=x.type==='password'?'text':'password';b.textContent=x.type==='password'?'Mostrar':'Ocultar'}}}catch(err){console.error(err);toast('Não foi possível concluir: '+(err.message||err))}
  });
  async function paymentModal(id){const c=(window.clients||[]).find(x=>String(x.id)===String(id));if(!c)return;const m=modal('je-pay','Confirmar pagamento',`<p><b>${esc(c.name)}</b></p><label>Valor recebido</label><input id="je-pay-value" class="je-input" type="number" step="0.01" value="${Number(c.amount||0)}"><div class="je-actions"><button class="je-btn je-success" id="je-pay-ok">Pagamento confirmado</button></div>`);m.querySelector('#je-pay-ok').onclick=async()=>{const amount=Number(m.querySelector('#je-pay-value').value||0);const now=new Date().toISOString();await rest('/rest/v1/clients?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({payment_status:'paid',paid_at:now,paid_amount:amount,last_charge_at:now})});await rest('/rest/v1/payment_history',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({owner_id:uid(),client_id:id,event_type:'payment',amount,paid_at:now,description:'Pagamento confirmado pelo painel',channel:'panel',metadata:{source:'jstech'}})});m.style.display='none';toast('Pagamento confirmado');if(typeof window.loadData==='function')await window.loadData();else location.reload()}}
  async function chargeClient(id,type){const c=(window.clients||[]).find(x=>String(x.id)===String(id));if(!c)return;const due=c.due_date||c.expire_date||'';const recent=await rest('/rest/v1/charge_history?client_id=eq.'+encodeURIComponent(id)+'&reminder_type=eq.'+encodeURIComponent(type)+'&order=created_at.desc&limit=1');if(recent?.[0]&&Date.now()-new Date(recent[0].created_at).getTime()<86400000){toast('Essa cobrança já foi registrada recentemente.');return}let pix='';try{const p=await rest('/rest/v1/panel_settings?owner_id=eq.'+encodeURIComponent(uid())+'&limit=1');pix=p?.[0]?.pix_copy_text||p?.[0]?.pix_key||''}catch(_){}const amount=Number(c.amount||0);const msg=`Olá ${c.name||''}! Lembrete JS Tech: seu vencimento é ${due?new Date(due+'T12:00:00').toLocaleDateString('pt-BR'): 'hoje'}. Valor: ${fmtMoney(amount)}.${pix?' Pix: '+pix:''}`;await rest('/rest/v1/charge_history',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({owner_id:uid(),client_id:id,channel:'whatsapp',reminder_type:type,message:msg,amount})});if(c.phone){const phone=String(c.phone).replace(/\D/g,'');window.open('https://wa.me/'+(phone.startsWith('55')?phone:'55'+phone)+'?text='+encodeURIComponent(msg),'_blank')}else{await navigator.clipboard?.writeText(msg);toast('Mensagem copiada; cliente sem telefone cadastrado.')}}
  async function historyClient(id){const rows=await rest('/rest/v1/charge_history?client_id=eq.'+encodeURIComponent(id)+'&order=created_at.desc&limit=50');const html=rows.length?`<table class="je-table"><tr><th>Data</th><th>Tipo</th><th>Canal</th><th>Valor</th></tr>${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('pt-BR')}</td><td>${esc(x.reminder_type||'manual')}</td><td>${esc(x.channel||'')}</td><td>${fmtMoney(x.amount)}</td></tr>`).join('')}</table>`:'<p>Nenhuma cobrança registrada.</p>';modal('je-history','Histórico de cobranças',html)}
  async function pixModal(){let p=[];try{p=await rest('/rest/v1/panel_settings?owner_id=eq.'+encodeURIComponent(uid())+'&limit=1')}catch(_){}const x=p[0]||{};const m=modal('je-pix','Configuração Pix',`<label>Chave Pix</label><input id="je-pix-key" class="je-input" value="${esc(x.pix_key||'')}"><br><label>Nome</label><input id="je-pix-name" class="je-input" value="${esc(x.pix_name||'')}"><br><label>Cidade</label><input id="je-pix-city" class="je-input" value="${esc(x.pix_city||'')}"><br><label>Texto para copiar</label><textarea id="je-pix-copy" class="je-input" rows="3">${esc(x.pix_copy_text||'')}</textarea><div class="je-actions"><button class="je-btn je-success" id="je-pix-save">Salvar Pix</button><button class="je-btn" id="je-pix-copy-btn">Copiar Pix</button></div>`);m.querySelector('#je-pix-copy-btn').onclick=()=>navigator.clipboard?.writeText(m.querySelector('#je-pix-copy').value||m.querySelector('#je-pix-key').value);m.querySelector('#je-pix-save').onclick=async()=>{const data={owner_id:uid(),pix_key:m.querySelector('#je-pix-key').value,pix_name:m.querySelector('#je-pix-name').value,pix_city:m.querySelector('#je-pix-city').value,pix_copy_text:m.querySelector('#je-pix-copy').value};if(x.id)await rest('/rest/v1/panel_settings?id=eq.'+encodeURIComponent(x.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});else await rest('/rest/v1/panel_settings',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});toast('Pix salvo');m.style.display='none'}}
  function activationModal(){modal('je-act','Ativação de aplicativos',`<div class="je-activation"><p>O site de ativação é aberto abaixo. Se o site bloquear iframe, use o botão.</p><iframe src="${ACTIVATION_URL}" title="Ativação de aplicativos"></iframe><div class="je-actions"><a class="je-btn je-primary" href="${ACTIVATION_URL}" target="_blank" rel="noopener">Abrir em nova aba</a></div></div>`)}
  async function backupNow(){const data={version:2,created_at:new Date().toISOString(),clients:window.clients||[],renewals:window.renewals||[],source:'jstech-panel'};await rest('/rest/v1/customer_backups',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({owner_id:uid(),backup:data})});toast('Backup automático salvo no banco.')}
  async function reportModal(){const rows=await rest('/rest/v1/payment_history?owner_id=eq.'+encodeURIComponent(uid())+'&event_type=eq.payment&order=paid_at.desc&limit=1000');const map={};rows.forEach(r=>{const k=(r.paid_at||r.created_at||'').slice(0,7);if(!map[k])map[k]={received:0,count:0};map[k].received+=Number(r.amount||0);map[k].count++});const clients=window.clients||[];const html=`<table class="je-table"><tr><th>Mês</th><th>Recebido</th><th>Pagamentos</th><th>Pendente atual</th><th>Custo atual</th><th>Lucro estimado</th></tr>${Object.keys(map).sort().reverse().slice(0,12).map(k=>{const pending=clients.filter(c=>c.payment_status!=='paid'&&!c.cancelled).reduce((s,c)=>s+Number(c.amount||0),0);const cost=clients.filter(c=>!c.cancelled).reduce((s,c)=>s+Number(c.monthly_cost??c.cost??0),0);return `<tr><td>${k}</td><td>${fmtMoney(map[k].received)}</td><td>${map[k].count}</td><td>${fmtMoney(pending)}</td><td>${fmtMoney(cost)}</td><td>${fmtMoney(map[k].received-cost)}</td></tr>`}).join('')}</table>`;modal('je-report','Relatório financeiro',html)}
  function advancedSearch(){const m=modal('je-search','Busca completa',`<input id="je-search-input" class="je-input" placeholder="Nome, telefone, usuário, MAC ou aplicativo"><div id="je-search-results"></div>`);const run=()=>{const q=m.querySelector('#je-search-input').value.toLowerCase().trim();const out=(window.clients||[]).filter(c=>{const s=[c.name,c.phone,c.app_name,c.email,c.login_username].join(' ').toLowerCase();return !q||s.includes(q)});m.querySelector('#je-search-results').innerHTML=`<table class="je-table"><tr><th>Cliente</th><th>Telefone</th><th>App</th><th>Status</th></tr>${out.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.app_name)}</td><td>${esc(c.payment_status||'pending')}</td></tr>`).join('')}</table>`};m.querySelector('#je-search-input').oninput=run;run()}
  function paymentStatus(c){if(c.cancelled)return ['Cancelado','je-overdue'];if(c.lifetime)return ['Vitalício','je-paid'];if(c.payment_status==='paid')return ['Pago','je-paid'];const d=c.due_date?new Date(c.due_date+'T23:59:59').getTime():0;return d&&d<Date.now()?['Atrasado','je-overdue']:['Pendente','je-pending']}
  function panel(){if(document.getElementById('jstech-finance'))return;const host=document.querySelector('main')||document.querySelector('.main')||document.body;const el=document.createElement('section');el.id='jstech-finance';el.className='jstech-enh';el.innerHTML=`<h3>💰 Financeiro e alertas</h3><div id="je-stats" class="je-grid"></div><div class="je-actions"><button class="je-btn je-primary" data-je-action="advanced">🔎 Busca completa</button><button class="je-btn je-success" data-je-action="pix">💠 Configurar Pix</button><button class="je-btn" data-je-action="report">📊 Relatório mensal</button><button class="je-btn" data-je-action="backup">💾 Backup agora</button><button class="je-btn je-warn" data-je-action="activation">🚀 Ativar aplicativo</button></div><div id="je-fin-table"></div>`;host.prepend(el);renderFinance()}
  function renderFinance(){const cs=window.clients||[];let paid=0,pending=0,over=0,received=0,cost=0;cs.forEach(c=>{const st=paymentStatus(c)[0];if(st==='Pago')paid++;else if(st==='Atrasado')over++;else if(st==='Pendente')pending++;received+=st==='Pago'?Number(c.paid_amount||c.amount||0):0;cost+=Number(c.monthly_cost??c.cost??0)});const stats=document.getElementById('je-stats');if(stats)stats.innerHTML=`<div class="je-stat">Pagos<b>${paid}</b></div><div class="je-stat">Pendentes<b>${pending}</b></div><div class="je-stat">Atrasados<b>${over}</b></div><div class="je-stat">Recebido<b>${fmtMoney(received)}</b></div><div class="je-stat">Custos<b>${fmtMoney(cost)}</b></div><div class="je-stat">Lucro estimado<b>${fmtMoney(received-cost)}</b></div>`;const t=document.getElementById('je-fin-table');if(t)t.innerHTML=`<table class="je-table"><tr><th>Cliente</th><th>Vencimento</th><th>Status</th><th>Ações</th></tr>${cs.slice(0,100).map(c=>{const [st,cl]=paymentStatus(c);return `<tr><td>${esc(c.name)}</td><td>${c.due_date?new Date(c.due_date+'T12:00:00').toLocaleDateString('pt-BR'):'-'}</td><td><span class="je-pill ${cl}">${st}</span></td><td><button class="je-btn je-success" data-je-action="payment" data-id="${c.id}">Pago</button> <button class="je-btn je-primary" data-je-action="charge" data-id="${c.id}" data-type="manual">Cobrar</button> <button class="je-btn" data-je-action="history" data-id="${c.id}">Histórico</button></td></tr>`}).join('')}</table>`}
  function reminders(){const cs=window.clients||[];const today=new Date();today.setHours(0,0,0,0);const alerts=[];cs.forEach(c=>{if(c.cancelled||c.lifetime||!c.due_date||c.payment_status==='paid')return;const d=new Date(c.due_date+'T00:00:00');const days=Math.round((d-today)/86400000);if([5,1,0].includes(days))alerts.push({c,days})});const host=document.getElementById('jstech-finance');if(host&&alerts.length){let a=document.getElementById('je-alerts');if(!a){a=document.createElement('div');a.id='je-alerts';a.className='jstech-enh';host.after(a)}a.innerHTML='<h3>🔔 Vencimentos próximos</h3>'+alerts.map(x=>`<div style="margin:7px 0"><b>${esc(x.c.name)}</b> — ${x.days===0?'vence hoje':x.days===1?'vence amanhã':'vence em 5 dias'} <button class="je-btn je-primary" data-je-action="charge" data-id="${x.c.id}" data-type="d${x.days}">Cobrar</button></div>`).join('')}}
  function enhancePasswords(){document.querySelectorAll('input[type="password"]').forEach((x,i)=>{if(x.dataset.jeDone)return;x.dataset.jeDone='1';const b=document.createElement('button');b.type='button';b.className='je-btn';b.textContent='Mostrar';b.dataset.jeAction='password';b.dataset.target=x.id||'';if(!x.id){x.id='je-pw-'+i;b.dataset.target=x.id}x.insertAdjacentElement('afterend',b)})}
  async function boot(){addStyle();panel();enhancePasswords();reminders();try{await backupNow()}catch(e){console.warn('backup automático:',e.message)}setInterval(()=>{renderFinance();reminders();enhancePasswords()},5000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,500);
  const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(()=>{renderFinance();enhancePasswords();reminders()},0);return r}}
})();
/* JSTECH ENHANCEMENTS END */

// JSTECH AUTO-INTEGRATION END

/* JSTECH_OLD_HOME_LOGIC */

/* JSTECH_OLD_HOME_LOGIC */
(function(){
  function hs(c){if(c.cancelled)return{label:'Cancelado',cls:'gray',overdue:false};if(c.lifetime)return{label:'Ativo',cls:'green',overdue:false};const d=diffDays(c.dueDate);return d<0?{label:'Atrasado',cls:'red',overdue:true}:{label:'Pendente',cls:'amber',overdue:false}}
  function renderOldHome(){const rows=document.getElementById('oldClientRows');if(!rows||typeof clients==='undefined')return;const list=clients.filter(c=>!c.cancelled).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'));const paid=list.filter(c=>c.payment==='paid'||c.payment_status==='paid'||c.status==='paid'),over=list.filter(c=>!c.lifetime&&diffDays(c.dueDate)<0),pending=list.filter(c=>!paid.includes(c)&&!c.lifetime&&diffDays(c.dueDate)>=0),received=paid.reduce((t,c)=>t+Number(c.value||0),0),costs=list.reduce((t,c)=>t+Number(c.cost||0),0);document.getElementById('oldPaid').textContent=paid.length;document.getElementById('oldPending').textContent=pending.length;document.getElementById('oldOverdue').textContent=over.length;document.getElementById('oldReceived').textContent=money(received);document.getElementById('oldCosts').textContent=money(costs);document.getElementById('oldProfit').textContent=money(received-costs);rows.innerHTML=list.map(c=>{const s=hs(c),a=s.overdue?`<div class="old-actions"><button onclick="renewClient('${c.id}')">Pago</button><button onclick="sendCharge('${c.id}')">Cobrar</button><button onclick="showHistory('${c.id}')">Histórico</button></div>`:'';return `<tr><td><strong>${escapeHTML(c.name)}</strong></td><td>${c.lifetime?'Vitalício':dateBR(c.dueDate)}</td><td><span class="badge ${s.cls}">${s.label}</span></td><td>${a}</td></tr>`}).join('');const e=document.getElementById('oldEmptyState');if(e)e.hidden=list.length!==0}
  window.renderOldHome=renderOldHome;
  function bind(){const m=(id,f)=>{const e=document.getElementById(id);if(e&&!e.dataset.bound){e.dataset.bound='1';e.addEventListener('click',f)}};m('oldNewClientBtn',()=>document.getElementById('newClientBtn')?.click());m('oldBackupBtn',()=>document.getElementById('exportBtn')?.click());m('oldAppsBtn',()=>document.querySelector('.sidebar .nav-item[data-view="apps"]')?.click());m('oldSearchBtn',()=>document.getElementById('searchInput')?.focus());m('oldReportBtn',()=>{const e=document.querySelector('.monthly-report');if(e){e.hidden=false;e.scrollIntoView({behavior:'smooth'})}});m('oldPixBtn',()=>typeof showToast==='function'&&showToast('Configuração do Pix disponível no cadastro de recebimento.'))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{renderOldHome();bind()});else{renderOldHome();bind()}
})();

/* Financeiro separado da página inicial */
(function(){
 function syncFinanceVisibility(){
  const financeActive=!!document.querySelector('.nav-item.active[data-view="finance"]');
  document.querySelectorAll('main > *').forEach(el=>{
   if(el.id==='resellersSection'||el.id==='androidAppsSection'||el.classList.contains('analytics')||el.classList.contains('monthly-report')||el.classList.contains('summary-grid')||el.classList.contains('topbar')||el.querySelector('#clientRows')) return;
   if((el.textContent||'').includes('Financeiro e alertas')) el.hidden=!financeActive;
  });
 }
 document.addEventListener('click',e=>{if(e.target.closest('.nav-item'))setTimeout(syncFinanceVisibility,50)});
 setInterval(syncFinanceVisibility,1000);
 setTimeout(syncFinanceVisibility,300);
})();
