/* JSTECH ENHANCEMENTS START
 * Camada complementar do painel JS Tech. Carregada pelo workflow no app.js.
 */
(function(){
  'use strict';
  const ACTIVATION_URL='https://ativacaodeaplicativos.com/';
  const OWNER_EMAIL='juliosirlene43@gmail.com';
  const fmtMoney=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  const todayISO=()=>new Date().toISOString().slice(0,10);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const toast=msg=>typeof window.showToast==='function'?window.showToast(msg):alert(msg);
  const uid=()=>window.session?.user?.id||window.currentUser?.id||null;
  async function rest(path,opts={}){
    const r=await fetch((window.SUPABASE_URL||'https://yifgptxujimzsjoeghte.supabase.co')+path,{...opts,headers:{apikey:window.SUPABASE_KEY||'',Authorization:'Bearer '+(window.session?.access_token||window.SUPABASE_KEY||''),'Content-Type':'application/json',...(opts.headers||{})}});
    if(!r.ok) throw new Error(await r.text());
    return r.status===204?null:r.json();
  }
  function addStyle(){if(document.getElementById('jstech-enh-style'))return;const s=document.createElement('style');s.id='jstech-enh-style';s.textContent=`
  .jstech-enh{margin:18px 0;padding:18px;border:1px solid var(--border,#ddd);border-radius:16px;background:var(--card,#fff);box-shadow:0 8px 28px #0000000d}.jstech-enh h3{margin:0 0 12px}.je-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.je-stat{padding:13px;border-radius:12px;background:var(--surface,#f5f6f8)}.je-stat b{display:block;font-size:20px}.je-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.je-btn{border:0;border-radius:10px;padding:9px 12px;cursor:pointer}.je-primary{background:#2563eb;color:#fff}.je-success{background:#16a34a;color:#fff}.je-warn{background:#f59e0b;color:#111}.je-danger{background:#dc2626;color:#fff}.je-input{width:100%;box-sizing:border-box;padding:9px;border:1px solid #ccc;border-radius:9px}.je-table{width:100%;border-collapse:collapse;margin-top:12px}.je-table th,.je-table td{padding:8px;border-bottom:1px solid #eee;text-align:left;font-size:13px}.je-pill{display:inline-block;padding:4px 8px;border-radius:999px;font-size:12px}.je-paid{background:#dcfce7;color:#166534}.je-pending{background:#fef3c7;color:#92400e}.je-overdue{background:#fee2e2;color:#991b1b}.je-modal{position:fixed;inset:0;background:#0008;z-index:99999;display:none;align-items:center;justify-content:center;padding:15px}.je-box{background:#fff;color:#111;width:min(760px,96vw);max-height:90vh;overflow:auto;border-radius:16px;padding:18px}.je-close{float:right;border:0;background:none;font-size:24px;cursor:pointer}.je-activation iframe{width:100%;height:520px;border:1px solid #ddd;border-radius:12px}.je-muted{opacity:.7;font-size:12px}`;document.head.appendChild(s)}
  function modal(id,title,body){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.className='je-modal';document.body.appendChild(m)}m.innerHTML=`<div class="je-box"><button class="je-close" data-je-close="${id}">×</button><h3>${title}</h3>${body}</div>`;m.style.display='flex';return m}
  document.addEventListener('click',async e=>{
    const close=e.target.closest('[data-je-close]');if(close){document.getElementById(close.dataset.jeClose).style.display='none';return}
    const b=e.target.closest('[data-je-action]');if(!b)return;const a=b.dataset.jeAction;
    try{if(a==='payment')await paymentModal(b.dataset.id);if(a==='charge')await chargeClient(b.dataset.id,b.dataset.type||'manual');if(a==='history')await historyClient(b.dataset.id);if(a==='pix')await pixModal();if(a==='activation')activationModal();if(a==='backup')await backupNow();if(a==='report')await reportModal();if(a==='advanced')advancedSearch();if(a==='password'){const x=document.getElementById(b.dataset.target);if(x){x.type=x.type==='password'?'text':'password';b.textContent=x.type==='password'?'Mostrar':'Ocultar'}}}catch(err){console.error(err);toast('Não foi possível concluir: '+(err.message||err))}
  });
  async function paymentModal(id){const c=(window.clients||[]).find(x=>String(x.id)===String(id));if(!c)return;const m=modal('je-pay','Confirmar pagamento',`<p><b>${esc(c.name)}</b></p><label>Valor recebido</label><input id="je-pay-value" class="je-input" type="number" step="0.01" value="${Number(c.amount||0)}"><div class="je-actions"><button class="je-btn je-success" id="je-pay-ok">Pagamento confirmado</button></div>`);m.querySelector('#je-pay-ok').onclick=async()=>{const amount=Number(m.querySelector('#je-pay-value').value||0);const now=new Date().toISOString();await rest('/rest/v1/clients?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({payment_status:'paid',paid_at:now,paid_amount:amount,last_charge_at:now})});await rest('/rest/v1/payment_history',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({owner_id:uid(),client_id:id,event_type:'payment',amount,paid_at:now,description:'Pagamento confirmado pelo painel',channel:'panel',metadata:{source:'jstech'}})});m.style.display='none';toast('Pagamento confirmado');if(typeof window.loadData==='function')await window.loadData();else location.reload()}}
  async function chargeClient(id,type){const c=(window.clients||[]).find(x=>String(x.id)===String(id));if(!c)return;const due=c.due_date||c.expire_date||'';const recent=await rest('/rest/v1/charge_history?client_id=eq.'+encodeURIComponent(id)+'&reminder_type=eq.'+encodeURIComponent(type)+'&order=created_at.desc&limit=1');if(recent?.[0]&&Date.now()-new Date(recent[0].created_at).getTime()<86400000){toast('Essa cobrança já foi registrada recentemente.');return}let pix='';try{const p=await rest('/rest/v1/panel_settings?owner_id=eq.'+encodeURIComponent(uid())+'&limit=1');pix=p?.[0]?.pix_copy_text||p?.[0]?.pix_key||''}catch(_){}const amount=Number(c.amount||0);const msg=`Olá ${c.name||''}! Lembrete JS Tech: seu vencimento é ${due?new Date(due+'T12:00:00').toLocaleDateString('pt-BR'): 'hoje'}. Valor: ${fmtMoney(amount)}.${pix?' Pix: '+pix:''}`;await rest('/rest/v1/charge_history',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({owner_id:uid(),client_id:id,channel:'whatsapp',reminder_type:type,message:msg,amount})});if(c.phone){const phone=String(c.phone).replace(/\D/g,'');window.open('https://wa.me/'+(phone.startsWith('55')?phone:'55'+phone)+'?text='+encodeURIComponent(msg),'_blank')}else{await navigator.clipboard?.writeText(msg);toast('Mensagem copiada; cliente sem telefone cadastrado.')}}
  async function historyClient(id){const rows=await rest('/rest/v1/charge_history?client_id=eq.'+encodeURIComponent(id)+'&order=created_at.desc&limit=50');const html=rows.length?`<table class="je-table"><tr><th>Data</th><th>Tipo</th><th>Canal</th><th>Valor</th></tr>${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('pt-BR')}</td><td>${esc(x.reminder_type||'manual')}</td><td>${esc(x.channel||'')}</td><td>${fmtMoney(x.amount)}</td></tr>`).join('')}</table>`:'<p>Nenhuma cobrança registrada.</p>';modal('je-history','Histórico de cobranças',html)}
  async function pixModal(){let p=[];try{p=await rest('/rest/v1/panel_settings?owner_id=eq.'+encodeURIComponent(uid())+'&limit=1')}catch(_){}const x=p[0]||{};const m=modal('je-pix','Configuração Pix',`<label>Chave Pix</label><input id="je-pix-key" class="je-input" value="${esc(x.pix_key||'')}"><br><label>Nome</label><input id="je-pix-name" class="je-input" value="${esc(x.pix_name||'')}"><br><label>Cidade</label><input id="je-pix-city" class="je-input" value="${esc(x.pix_city||'')}"><br><label>Texto para copiar</label><textarea id="je-pix-copy" class="je-input" rows="3">${esc(x.pix_copy_text||'')}</textarea><div class="je-actions"><button class="je-btn je-success" id="je-pix-save">Salvar Pix</button><button class="je-btn" id="je-pix-copy-btn">Copiar Pix</button></div>`);m.querySelector('#je-pix-copy-btn').onclick=()=>navigator.clipboard?.writeText(m.querySelector('#je-pix-copy').value||m.querySelector('#je-pix-key').value);m.querySelector('#je-pix-save').onclick=async()=>{const data={owner_id:uid(),pix_key:m.querySelector('#je-pix-key').value,pix_name:m.querySelector('#je-pix-name').value,pix_city:m.querySelector('#je-pix-city').value,pix_copy_text:m.querySelector('#je-pix-copy').value};if(x.id)await rest('/rest/v1/panel_settings?id=eq.'+encodeURIComponent(x.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});else await rest('/rest/v1/panel_settings',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});toast('Pix salvo');m.style.display='none'}}
  function activationModal(){modal('je-act','Ativação de aplicativos',`<div class="je-activation"><p>O site de ativação é aberto abaixo. Se o site bloquear iframe, use o botão.</p><iframe src="${ACTIVATION_URL}" title="Ativação de aplicativos"></iframe><div class="je-actions"><a class="je-btn je-primary" href="${ACTIVATION_URL}" target="_blank" rel="noopener">Abrir em nova aba</a></div></div>`)}
  async function backupNow(){const data={version:2,created_at:new Date().toISOString(),clients:window.clients||[],renewals:window.renewals||[],source:'jstech-panel'};await rest('/rest/v1/customer_backups',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({owner_id:uid(),backup:data})});toast('Backup automático salvo no banco.')}
  async function reportModal(){const rows=await rest('/rest/v1/payment_history?owner_id=eq.'+encodeURIComponent(uid())+'&event_type=eq.payment&order=paid_at.desc&limit=1000');const map={};rows.forEach(r=>{const k=(r.paid_at||r.created_at||'').slice(0,7);if(!map[k])map[k]={received:0,count:0};map[k].received+=Number(r.amount||0);map[k].count++});const clients=window.clients||[];const html=`<table class="je-table"><tr><th>Mês</th><th>Recebido</th><th>Pagamentos</th><th>Pendente atual</th><th>Custo atual</th><th>Lucro estimado</th></tr>${Object.keys(map).sort().reverse().slice(0,12).map(k=>{const pending=clients.filter(c=>c.payment_status!=='paid'&&!c.cancelled).reduce((s,c)=>s+Number(c.amount||0),0);const cost=clients.filter(c=>!c.cancelled).reduce((s,c)=>s+Number(c.monthly_cost??c.cost??0),0);return `<tr><td>${k}</td><td>${fmtMoney(map[k].received)}</td><td>${map[k].count}</td><td>${fmtMoney(pending)}</td><td>${fmtMoney(cost)}</td><td>${fmtMoney(map[k].received-cost)}</td></tr>`}).join('')}</table>`;modal('je-report','Relatório financeiro',html)}
  function advancedSearch(){const m=modal('je-search','Busca completa',`<input id="je-search-input" class="je-input" placeholder="Nome, telefone, usuário, MAC ou aplicativo"><div id="je-search-results"></div>`);const run=()=>{const q=m.querySelector('#je-search-input').value.toLowerCase().trim();const out=(window.clients||[]).filter(c=>{const s=[c.name,c.phone,c.app_name,c.email,c.login_username].join(' ').toLowerCase();return !q||s.includes(q)});m.querySelector('#je-search-results').innerHTML=`<table class="je-table"><tr><th>Cliente</th><th>Telefone</th><th>App</th><th>Status</th></tr>${out.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.app_name)}</td><td>${esc(c.payment_status||'pending')}</td></tr>`).join('')}</table>`};m.querySelector('#je-search-input').oninput=run;run()}
  function paymentStatus(c){if(c.cancelled)return ['Cancelado','je-overdue'];if(c.lifetime)return ['Vitalício','je-paid'];if(c.payment_status==='paid')return ['Pago','je-paid'];const d=c.due_date?new Date(c.due_date+'T23:59:59').getTime():0;return d&&d<Date.now()?['Atrasado','je-overdue']:['Pendente','je-pending']}
  function panel(){if(document.getElementById('jstech-finance'))return;const host=document.querySelector('main')||document.querySelector('.main')||document.body;const el=document.createElement('section');el.id='jstech-finance';el.className='jstech-enh';el.innerHTML=`<h3>💰 Financeiro e alertas</h3><div id="je-stats" class="je-grid"></div><div class="je-actions"><button class="je-btn je-primary" data-je-action="advanced">🔎 Busca completa</button><button class="je-btn je-success" data-je-action="pix">💠 Configurar Pix</button><button class="je-btn" data-je-action="report">📊 Relatório mensal</button><button class="je-btn" data-je-action="backup">💾 Backup agora</button><button class="je-btn je-warn" data-je-action="activation">🚀 Ativar aplicativo</button></div><div id="je-fin-table"></div>`;host.prepend(el);renderFinance()}
  function renderFinance(){const cs=window.clients||[];let paid=0,pending=0,over=0,received=0,cost=0;cs.forEach(c=>{const st=paymentStatus(c)[0];if(st==='Pago')paid++;else if(st==='Atrasado')over++;else if(st==='Pendente')pending++;received+=st==='Pago'?Number(c.paid_amount||c.amount||0):0;cost+=Number(c.monthly_cost??c.cost??0)});const stats=document.getElementById('je-stats');if(stats)stats.innerHTML=`<div class="je-stat">Pagos<b>${paid}</b></div><div class="je-stat">Pendentes<b>${pending}</b></div><div class="je-stat">Atrasados<b>${over}</b></div><div class="je-stat">Recebido<b>${fmtMoney(received)}</b></div><div class="je-stat">Custos<b>${fmtMoney(cost)}</b></div><div class="je-stat">Lucro estimado<b>${fmtMoney(received-cost)}</b></div>`;const t=document.getElementById('je-fin-table');if(t)t.innerHTML=`<table class="je-table"><tr><th>Cliente</th><th>Vencimento</th><th>Status</th><th>Ações</th></tr>${cs.slice(0,100).map(c=>{const [st,cl]=paymentStatus(c);return `<tr><td>${esc(c.name)}</td><td>${c.due_date?new Date(c.due_date+'T12:00:00').toLocaleDateString('pt-BR'):'-'}</td><td><span class="je-pill ${cl}">${st}</span></td><td><button class="je-btn je-success" data-je-action="payment" data-id="${c.id}">Pago</button> <button class="je-btn je-primary" data-je-action="charge" data-id="${c.id}" data-type="manual">Cobrar</button> <button class="je-btn" data-je-action="history" data-id="${c.id}">Histórico</button></td></tr>`}).join('')}</table>`}
  function reminders(){const cs=window.clients||[];const today=new Date();today.setHours(0,0,0,0);const alerts=[];cs.forEach(c=>{if(c.cancelled||c.lifetime||!c.due_date||c.payment_status==='paid')return;const d=new Date(c.due_date+'T00:00:00');const days=Math.round((d-today)/86400000);if([5,1,0].includes(days))alerts.push({c,days})});const host=document.getElementById('jstech-finance');if(host&&alerts.length){let a=document.getElementById('je-alerts');if(!a){a=document.createElement('div');a.id='je-alerts';a.className='jstech-enh';host.after(a)}a.innerHTML='<h3>🔔 Vencimentos próximos</h3>'+alerts.map(x=>`<div style="margin:7px 0"><b>${esc(x.c.name)}</b> — ${x.days===0?'vence hoje':x.days===1?'vence amanhã':'vence em 5 dias'} <button class="je-btn je-primary" data-je-action="charge" data-id="${x.c.id}" data-type="d${x.days}">Cobrar</button></div>`).join('')}}
  function enhancePasswords(){document.querySelectorAll('input[type="password"]').forEach((x,i)=>{if(x.dataset.jeDone)return;x.dataset.jeDone='1';const b=document.createElement('button');b.type='button';b.className='je-btn';b.textContent='Mostrar';b.dataset.jeAction='password';b.dataset.target=x.id||'';if(!x.id){x.id='je-pw-'+i;b.dataset.target=x.id}x.insertAdjacentElement('afterend',b)})}
  async function boot(){addStyle();panel();enhancePasswords();reminders();try{await backupNow()}catch(e){console.warn('backup automático:',e.message)}setInterval(()=>{renderFinance();reminders();enhancePasswords()},5000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,500);
  const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(()=>{renderFinance();enhancePasswords();reminders()},0);return r}}
})();
/* JSTECH ENHANCEMENTS END */
